### DISCUSSION TITLE
invalid character 'C' looking for beginning of value on command "hydra clients create"

### DISCUSSION THREAD

**Discussion by drgarcia1986** [ory/hydra#2280] [Q&A] [answered]
Hi, I tried to run hydra (with docker) on my machine with this `docker-compose.yaml`:

```yaml
version: '3.7'
services:

  hydra-migrate:
    image: oryd/hydra:v1.9.0-alpha.3
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=<my-secret>
    command:
      migrate sql -e --yes
    networks:
      - intranet

  hydra:
    image: oryd/hydra:v1.9.0-alpha.3
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=<my-secret>
    networks:
      - intranet
    depends_on:
      - hydra-migrate
    restart: on-failure

  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    networks:
      - intranet

  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:v1.9.0-alpha.3
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - intranet

networks:
  intranet:
```

Everything looks ok until I tried to create a hydra client:

```bash
$ docker-compose -f ory-hydra-postgres.yml exec hydra \
    hydra clients create \
    --endpoint http://127.0.0.1:4445/ \
    --id my-client \
    --secret secret \
    -g client_credentials
```

After that command I received this error:

```
You should not provide secrets using command line flags, the secret might leak to bash history and similar systems
The request failed with the following error message:
invalid character 'C' looking for beginning of value
```

Looks like a Json decode error, but I don't know why.
Is it an issue?

**Comment by drgarcia1986** [comment, marked as answer]
I changed a bit the compose file and now it's work 🤔 
```yml
version: '3.7'
services:

  hydra-migrate:
    image: oryd/hydra:v1.9.0-alpha.3
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=<my-secret>
    command:
      migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - 
        type: bind
        source: ./contrib/quickstart/5-min
        target: /etc/config/hydra
    networks:
      - intranet

  hydra:
    image: oryd/hydra:v1.9.0-alpha.3
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=<my-secret>
    command: serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
    volumes:
      - 
        type: bind
        source: ./contrib/quickstart/5-min
        target: /etc/config/hydra
    networks:
      - intranet
    depends_on:
      - hydra-migrate
    restart: on-failure

  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    networks:
      - intranet

  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:v1.9.0-alpha.3
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - intranet

networks:
  intranet:
```

the big deal is that I added the `hydra.yml` file:
```yml
serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://127.0.0.1:4444
  consent: http://127.0.0.1:3000/consent
  login: http://127.0.0.1:3000/login
  logout: http://127.0.0.1:3000/logout

secrets:
  system:
    - <my-secret>

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis

```
Is there an explanation for it?
