### DISCUSSION TITLE
bug: urls_consent does not result in expected change

### DISCUSSION THREAD

**Discussion by wibed** [ory/hydra#2308] [Q&A] [answered]
I expect me to misunderstand a fundamental concept, so I open a discussion here, instead of an issue:

I add following to my configuration file `- URLS_CONSENT=http://192.168.5.10`
to multiple locations. but it seems it has no effect. when the client accepts the login request it is returned
a redirect to: 
`http://127.0.0.1:4444/oauth2/auth?client_id=login_client&login_verifier=aced6361a8b8429991ef48dc1bf494c0&nonce=ybzvkaqknkrwftltyikreybg&redirect_uri=http%3A%2F%2Ftest.test&response_type=code&scope=offline+openid&state=oddpovrpkdkhtnqtvjggvejh`

I am running a modified quickstart.yml from the repo and starting the service with docker-compose.
no other modifications have been made. here is the modified configuration file for good measure:
```
###########################################################################
#######             FOR DEMONSTRATION PURPOSES ONLY                 #######
###########################################################################
#                                                                         #
# If you have not yet read the tutorial, do so now:                       #
#  https://www.ory.sh/docs/hydra/5min-tutorial                            #
#                                                                         #
# This set up is only for demonstration purposes. The login               #
# endpoint can only be used if you follow the steps in the tutorial.      #
#                                                                         #
###########################################################################

version: '3.7'

services:

  hydra:
    image: oryd/hydra:v1.9.0-sqlite
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
    volumes:
      -
        type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      -
        type: bind
        source: ./contrib/quickstart/5-min
        target: /etc/config/hydra
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - URLS_LOGIN=http://192.168.5.10
      - URLS_CONSENT=http://192.168.5.10
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - intranet

  hydra-migrate:
    image: oryd/hydra:v1.9.0-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    command:
      migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      -
        type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      -
        type: bind
        source: ./contrib/quickstart/5-min
        target: /etc/config/hydra
    restart: on-failure
    networks:
      - intranet

  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
      - URLS_CONSENT=http://192.168.5.10
    image: oryd/hydra-login-consent-node:v1.9.0
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - intranet

networks:
  intranet:

volumes:
  hydra-sqlite:
  ```
