### DISCUSSION TITLE
CORS for hybrid mobile apps

### DISCUSSION THREAD

**Discussion by PeteMac88** [ory/hydra#2396] [Q&A] [answered]
Hey there,
we are developing a hybrid mobile app and want to use our central auth server. I am currently getting a CORS error saying no 'Access-Control-Allow-Origin' is set which makes sense since its not enabled. We will also have some web apps that run under a specific domain using the auth server. 

My idea here is following setting:
```
public:
    cors:
      enabled: true
      allowed_origins:
        - https://domain.com
        - https://*.domain.com
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
      exposed_headers:
        - Content-Type
```
This will enable all the web apps under the same domain to use the public hydra endpoints. For the mobile clients we could add the `allowed_cors_origins` to allow requests from the devices which sending the requests from orginin `capacitor://localhost` (Android) or `http://localhost` (iOS) right?

The only problem I see here is that the [client library](https://github.com/openid/AppAuth-JS) we are using makes a request in the beginning to read the openid-configuration which is already blocked.

What is your recommendation for CORS settings in this case? Is it safe to use CORS here?

Thanks for your help in advance :)
