### DISCUSSION TITLE
Overwrite the end_session_endpoint in hydra config

### DISCUSSION THREAD

**Discussion by pommelinho** [ory/hydra#2471] [Q&A] [answered]
Hey!

It is possible to overwrite token url and auth url via the hydra config.

https://www.ory.sh/hydra/docs/reference/configuration

```
webfinger:
  ## oidc_discovery ##
  #
  # Configures OpenID Connect Discovery (/.well-known/openid-configuration).
  #
  oidc_discovery:
    ## token_url ##
    #
    # Overwrites the OAuth2 Token URL
    #
    # Examples:
    # - https://my-service.com/oauth2/token
    #
    # Set this value using environment variables on
    # - Linux/macOS:
    #    $ export WEBFINGER_OIDC_DISCOVERY_TOKEN_URL=<value>
    # - Windows Command Line (CMD):
    #    > set WEBFINGER_OIDC_DISCOVERY_TOKEN_URL=<value>
    #
    token_url: https://my-service.com/oauth2/token

    ## auth_url ##
    #
    # Overwrites the OAuth2 Auth URL
    #
    # Examples:
    # - https://my-service.com/oauth2/auth
    #
    # Set this value using environment variables on
    # - Linux/macOS:
    #    $ export WEBFINGER_OIDC_DISCOVERY_AUTH_URL=<value>
    # - Windows Command Line (CMD):
    #    > set WEBFINGER_OIDC_DISCOVERY_AUTH_URL=<value>
    #
    auth_url: https://my-service.com/oauth2/auth
```

Why is it not possible to also overwrite the **end_session_endpoint** here?
Is there any reason for this?
