### DISCUSSION TITLE
Why two different parameters for Private Key in YAML config?

### DISCUSSION THREAD

**Discussion by pha3z** [ory/hydra#2587] [Q&A] [answered]
I do not understand why the example YAML config file shows "cert" and "key" with the same comment.
What is the difference between these two lines?

```
tls:
    ## cert - Configures the private key (pem encoded).
    cert:
      path: /path/to/file.pem

    ## key - Configures the private key (pem encoded).
    key:
      path: /path/to/file.pem
```
