### DISCUSSION TITLE
Sqlite3 commandline syntax for hydra migrate and hydra serve

### DISCUSSION THREAD

**Discussion by ganeshkbhat** [ory/hydra#2593] [Q&A] [answered]
I have create a file called db.sqlite using touch command. I do not have sqlite3.exe installed in my windows machine. Migrate and server commands do not work  and gives error: 

`time=2021-06-27T09:59:56+05:30 level=fatal msg=dsn must be set audience=application service_name=ORY Hydra service_version=master`

I am using Windows machine. Any recommendations here on the command line I need to add for `hydra migrate sql` and `hydra serve all` commands? Please share appropriate command line syntax for `hydra migrate` and `hydra serve`. I am using the command line in windows 10 and I have built the hydra executable in my system using go build command

**`UPDATE` for someone struggling to get this right to get the test environment for SQLite set up (Post Discussions):**

1. Use the executable provided link below or build it yourself using the `-tags sqlite` command
2. Run the command `hydra migrate sql`
3. Run the command `hydra serer all --dangerous-force-http -c hydra.yml`

The hydra .yml file I used is like below, which is in the test folder (used for hydra tests) `hydrarepo/test/conformance/hydra/config` and the certificates are inside `hydrarepo/test/conformance/ssl`:

```
serve:
  cookies:
    same_site_mode: Lax
  tls:
    cert:
      # path: /etc/ssl/certs/ory-conformity.crt
      path: ./test/conformance/ssl/ory-conformity.crt
    key:
      # path: /etc/ssl/private/ory-conformity.key
      path: ./test/conformance/ssl/ory-conformity.key

log:
  level: trace
  format: json

urls:
  self:
    issuer: https://hydra:4444/
  consent: http://consent:3000/consent
  login: http://consent:3000/login
  logout: http://consent:3000/logout

secrets:
  system:
    - test

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: test
  dynamic_client_registration:
    default_scope:
      - email
      - offline_access
      - openid
      - address
      - phone
      - profile

oauth2:
  hashers:
    bcrypt:
      cost: 4
  session:
    encrypt_at_rest: false

# webfinger.oidc_discovery.client_registration_url

webfinger:
  oidc_discovery:
    supported_claims:
      - email
      - email_verified
      - phone_number
      - phone_number_verified
      - name
      - given_name
      - family_name
      - website
      - zoneinfo
      - birthdate
      - gender
      - profile
      - preferred_username
      - middle_name
      - locale
      - picture
      - updated_at
      - nickname
      - address
    supported_scope:
      - email
      - offline_access
      - openid
      - address
      - phone
      - profile
    userinfo_url: https://hydra:4444/userinfo
    token_url: https://hydra:4444/oauth2/token
    jwks_url: https://hydra:4444/.well-known/jwks.json
    client_registration_url: https://hydra:4445/clients


```
