### DISCUSSION TITLE
DSN connection string looks like a SQLite connection, but SQLite support was not built into the binary.

### DISCUSSION THREAD

**Discussion by kishorp-github** [ory/hydra#2703] [Q&A] [answered]
Trying to run hydra on minikube. Not sure why I am getting this error. I have set DSN=memory.
I am stuck here. Please help. @aeneasr 

time=2021-08-26T15:38:41Z level=fatal msg=Unable to create service registry. audience=application error=map[message:the DSN connection string looks like a SQLite connection, but SQLite support was not built into the binary. Please check if you have downloaded the correct binary or are using the correct Docker Image. Binary archives and Docker Images indicate SQLite support by appending the -sqlite suffix] service_name=ORY Hydra service_version=v1.10.5

I am using this container:
```
      containers:
        - name: hydra
          image: 'oryd/hydra:v1.10.5'
          imagePullPolicy: IfNotPresent
          command: ['hydra']
          volumeMounts:
            - name: hydra-config-volume
              mountPath: /etc/config
              readOnly: true
          args: ['serve', 'all']
          ports:
            - name: http-public
              containerPort: 4444
              protocol: TCP
            - name: http-admin
              containerPort: 4445
              protocol: TCP
```
