### DISCUSSION TITLE
Setting up Ory Hydra on Remote Server issues

### DISCUSSION THREAD

**Discussion by StefanVrecic** [ory/hydra#2711] [Q&A] [answered]
**What I want to achieve:**
Set up ory-hydra following 5 min tutorial on Remote, where I can access it from my browser at xxx.xxx.xxx.xxx:5555 and follow through the flow to get the token

**What I tried:**
I have gone through the docs.

I have tried using the hydra-login-consent-node on 3001, with exporting 
 ```HYDRA_ADMIN_URL=http://127.0.0.1:4445```

Following the 5 min tutorial, copying and pasting all the commands. It seems to work fine on my local machine, I can login and grant permission and get the token. And it goes through the hydra-login-consent-node endpoints.

On my remote Ubuntu 20.04 LTS server, I tried running the same 5-min tutorial commands and then accessing it from my browser as xxx.xxx.xxx.xxx:5555. When I hit the 'Authorize application' I get : ... **The OAuth2 request resulted in an error. Error: Invalid_request**

I tried setting the the contrib/quickstart/5-min/hydra.yml to 

a) xxx.xxx.xxx.xxx (my server)
b) and also left it as 127.0.0.1 with the 3001
as below:

```
urls:
  self:
    issuer: http://xxx.xxx.xxx.xxx:4444
  consent: http://xxx.xxx.xxx.xxx:3001/consent
  login: http://xxx.xxx.xxx.xxx:3001/login
  logout: http://xxx.xxx.xxx.xxx:3001/logout
  ```

I still get the error:
**The OAuth2 request resulted in an error. Error: Invalid_request**

So I looked at the 'Common Problems' at https://www.ory.sh/hydra/docs/next/debug/
There are some suggestions on commands eg.
```
hydra clients get --endpoint http://ory-hydra the-client-id
```

I tried running this, as follows to get the container ID

docker container ls
```
CONTAINER ID   IMAGE                                   COMMAND                  CREATED       STATUS       PORTS                                                                                                      NAMES
a50791a4a029   oryd/hydra:v1.10.5                      "hydra serve -c /etc…"   2 hours ago   Up 2 hours   0.0.0.0:4444-4445->4444-4445/tcp, :::4444-4445->4444-4445/tcp, 0.0.0.0:5555->5555/tcp, :::5555->5555/tcp   hydra_hydra_1
873a6c99963e   oryd/hydra-login-consent-node:v1.10.5   "/bin/sh -c 'npm run…"   2 hours ago   Up 2 hours   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                  hydra_consent_1
29f473b47b0d   postgres:9.6                            "docker-entrypoint.s…"   8 days ago    Up 8 days    5432/tcp                                                                                                   ory-hydra-example--postgres
23aa5e0ae31b   postgres:9.6                            "docker-entrypoint.s…"   9 days ago    Up 2 hours   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                                  hydra_postgresd_1
```

```sudo docker-compose -it hydra_hydra_1 hydra clients get``` from https://www.ory.sh/hydra/docs/cli/hydra-clients-get/ 

This just ends up with a non responsive terminal which didn't even respond to ^C. Eventually it ended with [227506] Failed to execute script docker-compose.

I also tried the help command anyway
```
sudo docker-compose -it hydra_hydra_1 hydra clients get --endpoint http://ory-hydra egg1
sudo docker-compose -it hydra_hydra_1 hydra clients get --endpoint http://localhost:4445 egg1
```
(yeah 'egg1' is the name of my client, ran out of ideas lol)

I just get a response with ```'Define and run multi-container applications with Docker. Usage : ....'```

I also tried setting the 5-min tutorial without hydra-login-consent-node. Same errors.

Can I please get some help, I've read over the documentation like 20 times and have tried setting all sorts of combinations for the urls, including localhost and remote addresses. Quite frankly I'm absolutely stuck ://

**Comment by Benehiko** [comment, marked as answer]
Hi @StefanVrecic 

First I'd like to mention that it would be better to run your Hydra instance behind a reverse proxy so that you do not need to expose any specific ports on your server. See our docs on [Preparing for Production](https://www.ory.sh/hydra/docs/production/).

Another pointer I could maybe give is try run the hydra server on your local machine and then access it from your local IP address (e.g. instead of 127.0.0.1 it would be something like 192.168.0...). 

There are a few hurdles to think of:
- The quickstart has not been configured to bind to the host IP, but instead uses localhost. 
- Added to this the 5-min guide assumes all callbacks are to localhost
- Hydra does not support a non-https callback on another IP except localhost. (e.g. http://192.168.0.... won't work)

So I would first configure the `hydra.yml` in the `contrib/quickstart/5-min` folder. In this case my **local** network ip is 192.168.0.137.

```yml
serve:
  admin:
    host: 0.0.0.0
  public:
    host: 0.0.0.0
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://192.168.0.137:4444
  consent: http://192.168.0.137:3000/consent
  login: http://192.168.0.137:3000/login
  logout: http://192.168.0.137:3000/logout

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
```

Next I will change the `consent` section in my `quickstart.yml`

```yml
consent:
    environment:
      - HYDRA_ADMIN_URL=http://192.168.0.137:4445
    image: oryd/hydra-login-consent-node:v1.10.6
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - intranet
```

Next I will create a client with a callback to https://192.168.0.137:5555 (since you're using the built in example web server).

```shell
docker-compose -f quickstart.yml exec hydra \
  hydra clients create \
  --endpoint http://192.168.0.137:4445/ \
  --id my-client \
  --secret secret \
  --scope openid,offline \
  --grant-types authorization_code,refresh_token \
  --response-types code,id_token \
  --callbacks https://192.168.0.137:5555/callback
```

Then I will run the server 

```shell
docker-compose -f quickstart.yml exec hydra \
  hydra token user \
  --endpoint http://192.168.0.137:4444/ \
  --client-id my-client \
  --client-secret secret \
  --port 5555 \
  --scope openid,offline \
  --redirect https://192.168.0.137:5555/callback \
  --https
```

which gives me this output

```shell
Setting up home route on https://127.0.0.1:5555/
Setting up callback listener on https://127.0.0.1:5555/callback
Press ctrl + c on Linux / Windows or cmd + c on OSX to end the process.
If your browser does not open automatically, navigate to:

	https://127.0.0.1:5555/

```

I will then navigate to https://192.168.0.137:5555 instead of the localhost.

Your browser will give you this:
![image](https://user-images.githubusercontent.com/18033717/132654556-2c47c929-2757-4a86-9caa-b122fce9fa39.png)

![image](https://user-images.githubusercontent.com/18033717/132654605-10aed38f-9368-49e2-8197-36ff6b569ae4.png)

![image](https://user-images.githubusercontent.com/18033717/132654678-fb593ec0-823c-49df-b5e9-d78367f13d52.png)

![image](https://user-images.githubusercontent.com/18033717/132654723-59fc12ef-6862-4d3f-9168-91bfe1e1009e.png)

![image](https://user-images.githubusercontent.com/18033717/132654776-839b73eb-4dbf-42c3-91e5-fe06353cd032.png)
