### DISCUSSION TITLE
Ory Hydra Login Flow - Error "Client does not exist"

### DISCUSSION THREAD

**Discussion by Zipunrar** [ory/hydra#3234] [Q&A] [answered]
Hi,

I am currently evaluating the Ory Hydra service for my company. I also already successfully tested kratos for user authentication.
However, I am struggeling with the Login Flow of Hydra.

My Setup:
* Hydra Version 1.11.9
* Hydra running in a local Docker container with SQLite Database
  ```bash
  d run --rm --name hydra --read-only -u 1000:1000 --net ory \
      --mount type=bind,dst=/data,src=%cd%/tmp/hydra/data \
      --mount type=bind,dst=/config,src=%cd%/tmp/hydra/config,ro \
      --mount type=bind,dst=/schemas,src=%cd%/tmp/hydra/schemas,ro  \
      --tmpfs /tmp:uid=1000,gid=1000,rw \
      -p 4444:4444 -p 4445:4445 \
      oryd/hydra serve all --dangerous-force-http  --config /config/config.yaml
  ```
* Hydra Configuration
  ```yaml
    dsn: sqlite:///data/hydra.sqlite?_fk=true&mode=rw
    webfinger:
      oidc_discovery:
        supported_claims:
          - email
          - username
          - roles
    oidc:
      subject_identifiers:
        supported_types:
          - public
          - pairwise
        pairwise:
          salt: FooBarBaz
      dynamic_client_registration:
        enabled: true
    urls:
      login: http://localhost:8080/security/login
      consent: http://localhost:8080/security/consent
      logout: http://localhost:8080/security/logout
      error: http://localhost:8080/security/login
      post_logout_redirect: http://localhost:8080/public/index.html
    strategies:
      access_token: jwt
      scope: exact
    ttl:
      access_token: 5m
      refresh_token: 1h
      id_token: 30m
      auth_code: 5m
      login_consent_request: 30m
    oauth2:
      session:
        encrypt_at_rest: false
      include_legacy_error_fields: true
      exclude_not_before_claim: false
      allowed_top_level_claims:
        - username
        - roles
        - email
        - uid
      expose_internal_errors: false
    secrets:
      cookie:
        - 8gw36fasefuafat72ft7fa5d252dd22a
      system:
        - 46gcsg367f7f73dfad356d561d2525d2
    sqa:
      opt_out: true
    dangerous-force-http: true
    serve:
      admin:
        tls:
          enabled: false
      public:
        tls:
          enabled: false
    log:
      leak_sensitive_values: false
      level: trace
  ```
* Client Settings
  ```json
  {
    "client_id": "frontend",
    "client_name": "Frontend",
    "redirect_uris": [
        "http://localhost:8080/public/index.html",
        "http://localhost:8080"
    ],
    "grant_types": [
        "authorization_code",
        "client_credentials",
        "refresh_token"
    ],
    "response_types": [
        "code",
        "id_token",
        "token"
    ],
    "scope": "ADMIN USER offline openid",
    "audience": [
        "backend",
        "frontend"
    ],
    "owner": "MyCompany",
    "policy_uri": "",
    "allowed_cors_origins": [],
    "tos_uri": "",
    "client_uri": "http://localhost:8080/public/index.html",
    "logo_uri": "",
    "contacts": [],
    "client_secret_expires_at": 0,
    "subject_type": "public",
    "jwks": {},
    "token_endpoint_auth_method": "none",
    "userinfo_signed_response_alg": "none",
    "created_at": "2022-08-25T11:33:17Z",
    "updated_at": "2022-08-26T11:12:01.432246Z",
    "post_logout_redirect_uris": [
        "http://localhost:8080/public/index.html"
    ],
    "backchannel_logout_uri": "http://localhost:4444/oauth2/sessions/logout",
    "metadata": {
        "sample": true,
        "apps": 2,
        "project": "xscore-security"
    },
    "authorization_code_grant_access_token_lifespan": "30m0s",
    "authorization_code_grant_id_token_lifespan": "30m0s",
    "authorization_code_grant_refresh_token_lifespan": "1h0m0s",
    "client_credentials_grant_access_token_lifespan": "5m0s",
    "implicit_grant_access_token_lifespan": "5m0s",
    "implicit_grant_id_token_lifespan": "10m0s",
    "jwt_bearer_grant_access_token_lifespan": "5m0s",
    "password_grant_access_token_lifespan": "5m0s",
    "password_grant_refresh_token_lifespan": "1h0m0s",
    "refresh_token_grant_id_token_lifespan": "30m0s",
    "refresh_token_grant_access_token_lifespan": "5m0s",
    "refresh_token_grant_refresh_token_lifespan": "1h0m0s"
  }
  ```

What I`m trying to do is making Postman requests to verify the API is working as I would expect in a sample scenario following the guide at https://www.ory.sh/docs/hydra/concepts/login.

I can initialize the login flow, using  `POST <hydra-public>/oauth2/auth` and a basic authorization header including a form encoded body with
```
client_id  = frontend
response_type = code
redirect_uri = http://localhost:8080
state = 6f6asf6fe62efsgftftf3333ee
scope = openid offline ADMIN
```
The response is the expected redirect to the login page of my app including the login_challenge from Hydra.

Next I just accept the login request using `GET <hydra-admin>/oauth2/auth/requests/login/accept` including the login challenge as query parameter and a json body of
```json
{
  "context": {"target":"backend"},
  "remember": true,
  "remember_for": 0,
  "subject": "zipunrar"
}
```

The response is a 200 Ok, including a json body with a "redirect_to" URL like 
```json
{
    "redirect_to": "http://localhost:4444/oauth2/auth?login_verifier=205b59e8c3d64de6907b06d25a7b4357"
}
```

However, calling this URL will result in 302 - Found with this error message:
```
<a
	href="http://localhost:8080/security/login?error=invalid_client&amp;error_description=Client+authentication+failed+%28e.g.%2C+unknown+client%2C+no+client+authentication+included%2C+or+unsupported+authentication+method%29.&amp;error_hint=The+requested+OAuth+2.0+Client+does+not+exist.">Found</a>.
```

I don't understand why the client should not exists if all other requests work well.
Can somebody please explain to me what I doing wrong here?
