### DISCUSSION TITLE
Can't create clients over MySQL

### DISCUSSION THREAD

**Discussion by orestevip** [ory/hydra#3237] [Q&A] [answered]
Hi all,
I'm trying to setup hydra without Docker.
I started with downloading the source code, runned it through VSCode with these args:
`            "args": ["serve", "all", "-c=hydra.yml", "--dangerous-force-http"]`

Here's hydra.yml:
```
serve:
  cookies:
    same_site_mode: Lax

dsn: mysql://*db-url*

urls:
  self:
    issuer: http://127.0.0.1:4444
  consent: http://127.0.0.1:3000/consent
  login: http://127.0.0.1:3000/login
  logout: http://127.0.0.1:3000/logout

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis

```

From Windows cmd, I'm trying to create my first client with:
`            hydra clients create --endpoint http://127.0.0.1:4445/ --id prova --secret my_secret -g client_credentials`
and this error happens:

`You should not provide secrets using command line flags, the secret might leak to bash history and similar systems
The request failed with the following error message:
{
  "error": "error",
  "error_description": "The error is unrecognizable"
}`

While in the VSCode debug console:
```
time=2022-08-31T12:36:39+02:00 level=info msg=started handling request http_request=map[headers:map[accept:application/json accept-encoding:gzip content-length:268 content-type:application/json user-agent:Go-http-client/1.1] host:127.0.0.1:4445 method:POST path:/clients query:<nil> remote:127.0.0.1:51694 scheme:http]
time=2022-08-31T12:36:39+02:00 level=error msg=An error occurred while handling a request audience=application error=map[message:mysql create: Error 1054: Unknown column 'authorization_code_grant_access_token_lifespan' in 'field list'] http_request=map[headers:map[accept:application/json accept-encoding:gzip content-length:268 content-type:application/json user-agent:Go-http-client/1.1] host:127.0.0.1:4445 method:POST path:/clients query:<nil> remote:127.0.0.1:51694 scheme:http] http_response=map[status_code:500] service_name=Ory Hydra service_version=master
time=2022-08-31T12:36:39+02:00 level=info msg=completed handling request http_request=map[headers:map[accept:application/json accept-encoding:gzip content-length:268 content-type:application/json user-agent:Go-http-client/1.1] host:127.0.0.1:4445 method:POST path:/clients query:<nil> remote:127.0.0.1:51694 scheme:http] http_response=map[headers:map[content-type:application/json] size:68 status:500 text_status:Internal Server Error took:100.9177ms]
```

I've already done manual migration with:
`hydra migrate sql *db-url*`

But I think the problem is still linked to the db migration.
Any clues on why this is happening? 

Thanks for your time.
