### DISCUSSION TITLE
Can't enable dangerousForceHttp

### DISCUSSION THREAD

**Discussion by EvaSzlifierzCriado** [ory/hydra#3272] [Q&A] [answered]
Hello,

When deploying version v1.11.8 to Kubernetes I try to enable --dangerous-force-http to the pod args, but the Pod doesn't recognise the flag. What am I doing wrong?

The error says: `time=2022-09-27T15:05:46Z level=fatal msg=Scheme from configuration key "urls.self.issuer" must be "https" unless --dangerous-force-http is passed but got scheme in value "http://127.0.0.1:4444/" is "http". To find out more, use "hydra help serve". audience=application service_name=Ory Hydra service_version=v1.11.8`

This is the hydra configuration in my values.yaml:

```
hydra:
    config:
      serve:
        public:
          port: 4444
        admin:
          port: 4445
        tls:
          allow_termination_from:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
      secrets: {}

      urls:
        self: {}

      # -- Enables database migration
    automigration:
      enabled: false
      # -- Configure the way to execute database migration. Possible values: job, initContainer
      # When set to job, the migration will be executed as a job on release or upgrade.
      # When set to initContainer, the migration will be executed when kratos pod is created
      # Defaults to job  
      type: job
      # -- Ability to override the entrypoint of the automigration container
      # (e.g. to source dynamic secrets or export environment dynamic variables)
      customCommand: []
      # -- Ability to override arguments of the entrypoint. Can be used in-depended of customCommand  
      # eg:
      # - sleep 5;
      #   - kratos
      customArgs: []

    dangerousForceHttp: true
    dangerousAllowInsecureRedirectUrls: true
```

Thanks for your help!
