### DISCUSSION TITLE
How to set the scopes in the payload of a jwt access_token in oauth2?

### DISCUSSION THREAD

**Discussion by sezanzeb** [ory/hydra#3430] [Q&A] [answered]
I would like to do this via an API without using the `hydra` CLI, but knowing how this works with the `hydra` command would also be helpful.

thanks :)

**Comment by sezanzeb** [comment, marked as answer]
this is how it works with the cli:

1. set 

```yml
oauth2:
    client_credentials:
        default_grant_allowed_scope: true
```

in hydras config so that the client scopes are always included in the jwt payload,

2. Use `--scope` in `hydra create client` or `hydra update client`

3. Check `.scp` of the payload, which is an array of strings, instead of `.scope`

also see https://github.com/ory/hydra/discussions/2809
