### DISCUSSION TITLE
Hydra login callback called twice

### DISCUSSION THREAD

**Discussion by drev74** [ory/hydra#3543] [Q&A]
Hello I'm running a self-hosted hydra with a basic react app with Vite . Here's my code:  :eyes: 
```ts
// login.ts
export function Login() {
  const [searchParams] = useSearchParams()

 useEffect(() => {
   const challenge = searchParams.get("login_challenge")
   console.log(`*** login challenge: ${challenge}`);
 })

return (
  <h2>Login Page</h2>
)
```
```yaml
# hydra.yml
version: v2.1.2

serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://localhost:4444
  consent: http://192.168.1.93:3000/consent
  login: http://192.168.1.93:3000/login
  logout: http://192.168.1.93:3000/logout

secrets:
  cookie:
    - youReallyNeedToChangeThis
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis

log:
  leak_sensitive_values: true
  level: debug
```
When I start my app, I see the following in console: `*** login challenge: c3c25a2237a84b41a02ca302eb94e47d`
Thus my login page was called TWICE by hydra. 

Is this a bug? Why would hydra make an extra dummy call in my case? :roll_eyes: 

Hydra ver: v2.1.2
React: 18.2.0
React-router-dom: 6.12.1
Vite: 4.3.9
