### DISCUSSION TITLE
Hydra not able to connect to Aurora

### DISCUSSION THREAD

**Discussion by Newbie112222** [ory/hydra#3547] [Q&A] [answered]
Hi,
I am using Hydra v2.0.1 and trying to connect to Aurora Postgres. I am seeing my pod fail with the error below. Any ideas what would be a fix for this?
EKS: 1.26

time=2023-06-15T19:03:19Z level=info msg=No tracer configured - skipping tracing setup audience=application service_name=Ory Hydra service_version=v2.0.1
time=2023-06-15T19:03:19Z level=warning msg=Unable to determine network, retrying. audience=application error=map[debug: message:Unable to locate the table reason: status:Internal Server Error status_code:500] service_name=Ory Hydra service_version=v2.0.1
time=2023-06-15T19:03:19Z level=error msg=Unable to create service registry. audience=application error=map[debug: message:Unable to locate the table reason: status:Internal Server Error status_code:500] service_name=Ory Hydra service_version=v2.0.1
Error: Unable to locate the table

It looks like i am able to connect to the DB but Hydra is not able to create the table.

FYI i am using the below quickstart template for my pod as a config:
```
serve:
  cookies:
    same_site_mode: Lax
dsn: MY_DB_URL

urls:
  self:
    issuer: http://127.0.0.1:4444
  consent: http://127.0.0.1:3000/consent
  login: http://127.0.0.1:3000/login
  logout: http://127.0.0.1:3000/logout

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
```
