### DISCUSSION TITLE
Token Webhook Authentication in Ory Hydra

### DISCUSSION THREAD

**Discussion by nicklobosco-clear** [ory/hydra#3721] [Q&A] [answered]
Hello! I'm trying to setup authentication for ory hydra's token_webhook. Following this doc: https://www.ory.sh/docs/hydra/guides/claims-at-refresh#webhook-authentication I tried to set the config in my hydra instance like: 

```
oauth2:
  token_hook:
    url: http://host.docker.internal:8081/webhook
    auth:
      type: api_key
      config:
        name: Oauth2-API-Key
        value: WEBHOOK_API_KEY
        in: header
```

but I'm getting the following error: 

``` 
ory-hydra-1          | Error: I[#/oauth2/token_hook] S[#/properties/oauth2/properties/token_hook/type] expected string, but got object
ory-hydra-1          | I[#/oauth2/token_hook] S[#/properties/oauth2/properties/token_hook/type] expected string, but got object
```

does webhook authentication only work for ory network and not for self hosted instances of ory hydra? thanks!

**Comment by acp9191** [comment, marked as answer]
I believe this was fixed in 2.2.0 thanks to this PR: https://github.com/ory/hydra/pull/3677. Are you running the latest version?

**Reply by nicklobosco-clear** [reply]
I am now, that worked thanks! It would be great if the docs https://www.ory.sh/docs/hydra/reference/configuration were updated with the latest format though

**Reply by vinckr** [reply]
Hello @nicklobosco-clear 
Apologies for the late followup here.
The config should update automatically 🤔 
What specifically is out of date?

**Reply by greenbeam-ita** [reply]
Hi, I guess @nicklobosco-clear try to say that hydra configuration reference is not updated with the syntax
```
oauth2:
  token_hook:
    url: http://host.docker.internal:8081/webhook
    auth:
      type: api_key
      config:
        name: Oauth2-API-Key
        value: WEBHOOK_API_KEY
        in: header
```

By the way, I'm running hydra and kratos self-hosted with docker in my local machine, I setup token_hook properly but anything seems happen.

**Hydra v2.2.0**

Configuration file successfully changed from hydra logs.

I try to use it to retrieve custom claims but seems this hook is totally ignored. (my oauth flow is in a row phase but it work properly).

I don't see any hook from hydra logs
