### ISSUE TITLE
docker-compose restart value is wrong

### ISSUE THREAD

**Issue by lopezator** [ory/hydra#1312]
**Describe the bug**

docker-compose `restart: unless-stopped` is not a docker-compose v2 valid value.

**To Reproduce**

See here:

https://docs.docker.com/compose/compose-file/compose-file-v2/#restart

Valid values are: 

```yaml
  - restart: no
  - restart: always
  - restart: on-failure
```

`unless-stopped` is a docker-compose v3 restart value, see here:

https://docs.docker.com/compose/compose-file/#restart

**Expected behavior**

Either update docker-compose file to v3 or change the `restart: unless-stopped` values to other v2 applicable value.
