### ISSUE TITLE
cors: Apply sane defaults for cors

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#1400]
Right now, setting up cors is painful. We should set defaults that allow CORS *to just work* (tm). These values must be set:

```
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE

      # A list of non simple headers the client is allowed to use with cross-domain requests.
      allowed_headers:
        - Authorization

      # Sets which headers (comma separated values) are safe to expose to the API of a CORS API specification
      exposed_headers:
        - Content-Type

      # Sets whether the request can include user credentials like cookies, HTTP authentication
      # or client side SSL certificates.
      allow_credentials: true
```
