### ISSUE TITLE
hydra migrate sql fails on 1.0.1, but works on 1.0.0

### ISSUE THREAD

**Issue by staffler-xyz** [ory/hydra#1571]
**Describe the bug**

When running the hydra migrate sql command, the connection is established with the database. However, afterwards the command `hydra migrate sql -e --yes` fails because of a parse error of the DSN.

**Reproducing the bug**

1. Setup with the `docker-compose.yml` from below
2. Run `docker-compose up`
3. Switch to `v1.0.0` and run `docker-compose up` again
The migration fails on 1.0.1, but works on 1.0.0.

*Server logs*

```
hydra-migrate_1  | Config file not found because "Config File ".hydra" Not Found in "[/]""
hydra-migrate_1  | migrate dsn set viper 2: mysql://root:passw@tcp(db:3306)/database?max_conns=20&max_idle_conns=4
hydra-migrate_1  | migrate dsn set viper 3: mysql://root:passw@tcp(db:3306)/database?max_conns=20&max_idle_conns=4
hydra-migrate_1  | Got dsn: mysql://root:passw@tcp(db:3306)/database?max_conns=20&max_idle_conns=4time="2019-09-19T13:52:08Z" level=info msg="No tracer configured - skipping tracing setup"
hydra-migrate_1  | time="2019-09-19T13:52:08Z" level=info msg="Establishing connection with SQL database backend" dsn="root:passw@tcp(db:3306)/database?parseTime=true://*:*@tcp(db:3306)/database?parseTime=true"
hydra-migrate_1  | time="2019-09-19T13:52:08Z" level=info msg="Successfully connected to SQL database backend" dsn="root:passw@tcp(db:3306)/database?parseTime=true://*:*@tcp(db:3306)/database?parseTime=true"
hydra-migrate_1  | Usage:
hydra-migrate_1  |   hydra migrate sql <database-url> [flags]
hydra-migrate_1  | 
hydra-migrate_1  | Flags:
hydra-migrate_1  |   -h, --help            help for sql
hydra-migrate_1  |   -e, --read-from-env   If set, reads the database connection string from the environment variable DSN or config file key dsn.
hydra-migrate_1  |   -y, --yes             If set all confirmation requests are accepted without user interaction.
hydra-migrate_1  | 
hydra-migrate_1  | Global Flags:
hydra-migrate_1  |       --config string     Config file (default is $HOME/.hydra.yaml)
hydra-migrate_1  |       --skip-tls-verify   Foolishly accept TLS certificates signed by unkown certificate authorities
hydra-migrate_1  | 
hydra-migrate_1  | 
hydra-migrate_1  | parse mysql://root:passw@tcp(db:3306)/database?max_conns=20&max_idle_conns=4: invalid port ":3306)" after host
```

*Server configuration*

```yaml
version: "3"
services:
  db:
    image: mariadb:10.0.36-xenial
    environment:
      MYSQL_ROOT_PASSWORD: 'passw'
      MYSQL_USER: 'user'
      MYSQL_PASS: 'pass'
      MYSQL_DATABASE: 'database'
    volumes:
      - data:/var/lib/mysql

  hydra-migrate:
    image: oryd/hydra:v1.0.0
    environment:
      - DSN=mysql://root:passw@tcp(db:3306)/database?max_conns=20&max_idle_conns=4
    command:
      migrate sql -e --yes
    restart: on-failure
    depends_on:
      - db

volumes:
  data:
```

**Expected behavior**

Migrations should be run.

**Environment**

* Version: v1.0.1
* Environment: ubuntu 16.04

**Additional context**

It may be a problem of parsing the DSN.
