### ISSUE TITLE
Create client command doesn't pass some arguments

### ISSUE THREAD

**Issue by paulmarshall** [ory/hydra#1584]
**Describe the bug**

The name and scope does not get set when creating client

**Reproducing the bug**

1. Build docker compose file (see below)

```
version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '500k'
    max-file: '5'
  driver: json-file

services:

  authserver:
    image: oryd/hydra:latest
    logging: *default-logging
    networks:
      - front-end
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve all --dangerous-force-http
    environment:
      - URLS_SELF_ISSUER=http://127.0.0.1:4444
      - URLS_CONSENT=http://127.0.0.1:3000/consent
      - URLS_LOGIN=http://127.0.0.1:3000/login
      - URLS_LOGOUT=http://127.0.0.1:3000/logout
      - DSN=memory
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_TYPES_SUPPORTED=public,pairwise
      - OIDC_SUBJECT_TYPE_PAIRWISE_SALT=youReallyNeedToChangeThis
    restart: unless-stopped

  authserver-setup:
    image: oryd/hydra:latest
    logging: *default-logging
    networks:
      - front-end
    depends_on:
      - authserver  
    command: 
      clients create  --id esper \
                      --name esper \
                      --callbacks http://localhost/callback \
                      --grant-types authorization_code,refresh_token \
                      --response-types code,id_token \
                      --scopes article.read \
                      --secret some-secret \
                      --skip-tls-verify \
                      --token-endpoint-auth-method none
    environment:
      - HYDRA_ADMIN_URL=http://authserver:4445

  identity:
    image: oryd/hydra-login-consent-node:v1.0.0-rc.10
    logging: *default-logging
    networks:
      - front-end
    ports:
      - "3000:3000"
    environment:
      - HYDRA_ADMIN_URL=http://authserver:4445
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    restart: unless-stopped

networks:
  front-end:

````
2) Run `docker-compose -f docker-compose.oauth.yml up -d --build`
3) Run `docker run --rm -it --network nexus_front-end --entrypoint hydra oryd/hydra:latest clients get esper --endpoint http://authserver:4445`

**Expected behavior**

Name and scopes to be populated correctly as per command args

BUT, get:
```
| CLIENT ID | NAME | RESPONSE TYPES |             SCOPE             | REDIRECT URIS |    GRANT TYPES     | TOKEN ENDPOINT AUTH METHOD |
|-----------|------|----------------|-------------------------------|---------------|--------------------|----------------------------|
| esper     |      | code           | offline_access offline openid |               | authorization_code | client_secret_basic        |
```

**Environment**

* Environment: Windows, Docker

**Additional context**
