### ISSUE TITLE
Using Discovery in combination with ory deploy documentation 

### ISSUE THREAD

**Issue by phal0r** [ory/hydra#1620]
**Describe the bug**

I used your documentation for docker deployment (https://www.ory.sh/docs/hydra/configure-deploy) to get started with Hydra. So far everything is working, unless I use autodiscovery of an oidc client (https://github.com/panva/node-openid-client). The returned authorization_endpoint is the docker internal dns name of hydra, which the browser cannot resolve. The documentation circumvents this behaviour by explicitly prodiving the url via `--auth-url https://localhost:9000/oauth2/auth \` (and not using discovery at all).

**Reproducing the bug**
Follow the documentation to set up Postgres + Hydra + Client. Use a oidc client implementation with auto discovery, which runs in the same docker network by providing `https://ory-hydra-example--hydra:4444` as discovery url. Discovery returns `https://ory-hydra-example--hydra:4444/oauth2/auth` as authorization_endpoint, which is not reachable by a browser.  

Setting URLS_SELF_PUBLIC to `http://localhost:9000` changes the userinfo endpoint to the public value, but not the authorization_endpoint.

**Expected behavior**

A way to use the docker setup described in https://www.ory.sh/docs/hydra/configure-deploy to set up an working environment including the discovery feature. Therefor the authorization_endpoint should use URLS_SELF_PUBLIC configuration, if set.

**Environment**

* Version: Hydra v1.0.3
* Environment: Docker, setup as described in https://www.ory.sh/docs/hydra/configure-deploy

**Comment by Anaxilaus** [comment]
You ran OIDC Discovery where hydra's public endpoints are at port 4444 in the docker network, no surprise. In the docs, you bond docker network's 4444 port with host's 9000 port. `/oauth2/auth` will be accessible at `localhost:9000/oauth2/auth`.

There's no URLS_SELF_PUBLIC, I believe you meant `URLS_SELF_ISSUER`. There's no bug.

**Comment by phal0r** [comment]
Hi @Anaxilaus 
thanks for your fast answer and I think my issue needs more context to describe the problem. Let me start:

The guide provides a docker setup, which deploys Postgres, Hydra, installs an OAuth2 Client in Hydra and sets up a dummy client instance to demonstrate the authorization flow. To support this flow, Hydra must be accessible from 2 different points:
- the webbrowser which performs the redirect
- the client backend to verify tokens, get userInfo and so on

This is why the client command looks like this:
```
docker run --rm -it \
  --network hydraguide \
  -p 9010:9010 \
  oryd/hydra:v1.0.8 \
  token user --skip-tls-verify \
    --port 9010 \
    *--auth-url https://localhost:9000/oauth2/auth \*
    *--token-url https://ory-hydra-example--hydra:4444/oauth2/token \*
    --client-id facebook-photo-backup \
    --client-secret some-secret \
    --scope openid,offline,photos.read
```

Since the client runs as a docker container, `localhost:9000` won't work, since it will try to connect to localhost inside the client docker container. This is why `token-url` is set to `https://ory-hydra-example--hydra:4444/oauth2/token`, which only works inside the docker network.

The browser however runs on the host os. Since Hydra is bound to port 9000 the browser can make redirects to `https://localhost:9000`. This is why the `auth-url` is set to `https://localhost:9000/oauth2/auth`. 

So the browser and the client backend need different urls to reach Hydra and these urls are not interchangable. The browser on the host has no access to the docker network and the client backend inside the docker container will resolve `localhost` to istelf inside the container.

This guide works, because `auth-url` and `token-url` are configured differently. However, if I want to achieve the same with the discovery feature, it must return the same differing urls, which it does not currently. This is why this setup does not work with the discovery feature. 

And to also come back to `URLS_SELF_PUBLIC`. The configuration (https://www.ory.sh/docs/hydra/configuration) states:

```
urls:
  self:
    # This value will be used as the "issuer" in access and ID tokens. It must be
    # specified and using HTTPS protocol, unless --dangerous-force-http is set. This should typically be equal
    # to the public value.
    issuer: https://localhost:4444/

    # This is the base location of the public endpoints of your ORY Hydra installation. This should typically be equal
    # to the issuer value. If left unspecified, it falls back to the issuer value.
    public: https://localhost:4444/
```
So from my understanding `URLS_SELF_PUBLIC` does exist and my interpretation is, that it exists to solve this issue with the differing urls reachable from outside browsers and docker containers inside the docker network.

Does this shed more light on my issue?
