### ISSUE TITLE
Support additional signing algorithms for OpenID Connect ID Tokens and OpenID Connect Userinfo

### ISSUE THREAD

**Issue by divinespear** [ory/hydra#1638]
**Describe the bug**

ES512 jwk keys make message like "Retrying in 15.000000 seconds.." on startup.

**Reproducing the bug**

1. start hydra.
2. drop RS256 keys of `hydra.jwt.access-token` and `hydra.openid.id-token`.
3. create ES512 keys of `hydra.jwt.access-token` and `hydra.openid.id-token`.
4. restart hydra.

*Server logs*

```
time="2019-11-18T19:57:49Z" level=info msg="No tracer configured - skipping tracing setup"
time="2019-11-18T19:57:49Z" level=info msg="Establishing connection with SQL database backend" dsn="postgres://*:*@auth-db:5432/***?sslmode=disable"
time="2019-11-18T19:57:49Z" level=info msg="Successfully connected to SQL database backend" dsn="postgres://*:*@auth-db:5432/***?sslmode=disable"
time="2019-11-18T19:57:49Z" level=info msg="Retrying in 0.100000 seconds..."
time="2019-11-18T19:57:49Z" level=info msg="Retrying in 0.200000 seconds..."
time="2019-11-18T19:57:49Z" level=info msg="Retrying in 0.400000 seconds..."
time="2019-11-18T19:57:49Z" level=info msg="Retrying in 0.800000 seconds..."
time="2019-11-18T19:57:50Z" level=info msg="Retrying in 1.600000 seconds..."
time="2019-11-18T19:57:52Z" level=info msg="Retrying in 3.200000 seconds..."
time="2019-11-18T19:57:55Z" level=info msg="Retrying in 6.400000 seconds..."
time="2019-11-18T19:58:01Z" level=info msg="Retrying in 12.800000 seconds..."
time="2019-11-18T19:58:14Z" level=info msg="Retrying in 15.000000 seconds..."
time="2019-11-18T19:58:29Z" level=info msg="Retrying in 15.000000 seconds..."
```

*Server configuration*

```
  hydra:
    image: "oryd/hydra:latest-alpine"
    depends_on:
      - db
    restart: always
    volumes:
      - "/home/divinespear/docker/data/***/hydra:/var/run/hydra"
    environment:
      LOG_LEVEL: debug
      SECRETS_SYSTEM: "***"
      DSN: "postgres://***:***@auth-db:5432/***?sslmode=disable"
      URLS_SELF_ISSUER: "https://127.0.0.1:9000"
      URLS_CONSENT: "http://172.18.0.13:3000/consent"
      URLS_LOGIN: "http://172.18.0.13:3000/login"
      URLS_LOGOUT: "http://172.18.0.13:3000/logout"
    ports:
      - 9000:4444
      - 9001:4445
    networks:
      static:
        ipv4_address: "172.18.0.12"

```

**Expected behavior**

1. ES512 keys should work as RS256 key does.
2. If cannot 1, should create new RS256 keys when no RS256 keys detected.

**Environment**

* Version: v1.0.9
* Environment: Docker (oryd/hydra:latest-alpine)
