### ISSUE TITLE
Make Logging Traceable

### ISSUE THREAD

**Issue by sawadashota** [ory/hydra#1680]
**Is your feature request related to a problem? Please describe.**

Jaeger provides a great distributed tracing system but it's not small cost for transition period of monolith to micro service: really few micro services. So now I need traceable logging until I install jaeger.

**Describe the solution you'd like**

Add logging configuration option like following

```yaml
serve:
  admin:
    ...
    additional_logging:
      header_tracing_id: ToTraceID
      header_span_id: ToSpanID
```

Then, reading `ToTraceID` and `ToSpanID` are read from HTTP headers and logging appears like this

```
 {"level":"info",...,"tracing_id": "xxxxxxxxxxxxxxx", "span_id", "xxxxxxxxxxxxxxx"}
```
