### ISSUE TITLE
Large latencies in sql-conn-query

### ISSUE THREAD

**Issue by inigohu** [ory/hydra#1755]
**Describe the bug**

I have some `sql-conn-query` spans that have large latencies when running this query:
`SELECT h.* FROM hydra_oauth2_consent_request_handled as h JOIN hydra_oauth2_consent_request as r ON (h.challenge = r.challenge) WHERE r.subject=$1 AND r.client_id=$2 AND r.skip=FALSE AND (h.error='{}' AND h.remember=TRUE) ORDER BY h.requested_at DES`

Some of them take up to 46798.673 ms, 7196.002 ms, or 4821.986 ms for example.

**Reproducing the bug**

Make API Request to with `curl https://mydomain/oauth2/auth`

*Server configuration*

```yaml
    LOG_LEVEL: "debug",
    SERVE_PUBLIC_PORT: "8080",
    SERVE_ADMIN_PORT: "9000",
    URLS_SELF_ISSUER: accountUrl,
    URLS_LOGIN: signInUrl + "/login",
    URLS_LOGOUT: signInUrl + "/logout",
    URLS_CONSENT: signInUrl + "/consent",
    URLS_ERROR: signInUrl + "/error",
    URLS_POST_LOGOUT_REDIRECT: appUrl,
    OIDC_SUBJECT_IDENTIFIERS_ENABLED: "public,pairwise",
    TTL_LOGIN_CONSENT_REQUEST: "1h",
    TTL_ACCESS_TOKEN: "1h",
    TTL_REFRESH_TOKEN: "2160h",  // 90 days in hours
    TTL_ID_TOKEN: "1h",
    TTL_AUTH_TOKEN: "10m",
```

**Expected behavior**

Lower latency

**Environment**

* Version: v1.0.9
* Environment: Docker in kubernetes
