### ISSUE TITLE
TLS keys issue after upgrade to 1.4.5

### ISSUE THREAD

**Issue by gkapkowski** [ory/hydra#1804]
**Describe the bug**
Hydra container does not start with error:
```
level=fatal msg="The configuration is invalid and could not be loaded." [config_key=serve.tls.cert]="allOf failed" [config_key=serve.tls.key]="allOf failed" [config_key=serve.tls]
="validation failed" config_file=/hydra.yaml
```

**Reproducing the bug**

I'm running hydra with custom configuration file.

```
$ docker run -it --volume (pwd)/core/hydra/hydra.yaml:/hydra.yaml --env DSN=postgres://localhost/db oryd/hydra:v1.4.5-alpine serve all --config /hydra.yaml             

FATA[0000] The configuration is invalid and could not be loaded.  [config_key=serve.tls.cert]="allOf failed" [config_key=serve.tls.key]="allOf failed" [config_key=serve.tls]="validation failed" config_file=/hydra.yaml
```

It was working in 1.4.2
```
$ docker run -it --volume (pwd)/core/hydra/hydra.yaml:/hydra.yaml --env DSN=postgres://localhost/db oryd/hydra:v1.4.2-alpine serve all --config /hydra.yaml

INFO[0000] No tracer configured - skipping tracing setup 
INFO[0000] Establishing connection with SQL database backend  dsn="postgres://*:*@postgres://localhost/db?"
```

_Server configuration_

```yaml
log:
  level: debug

webfinger:
  oidc_discovery:
    client_registration_url: https://domain/register

serve:
  tls:
    key:
      path: /run/secrets/hydra_tls_key

    cert:
      path: /run/secrets/hydra_tls_cert

oidc:
  subject_identifiers:
    enabled:
      - public

  dynamic_client_registration:
    default_scope:
      - openid

urls:
  self:
    issuer: https://domain/

  login: https://domain/login
  consent: https://domain/consent

secrets:
  system:
    - ...
```
-->

**Expected behavior**

Hydra should work as in version 1.4.2

**Environment**

- Version: v1.4.5
- Environment: Alpine, Docker
