### ISSUE TITLE
Refreshing a deleted token returns 400 instead of 401

### ISSUE THREAD

**Issue by jimmya** [ory/hydra#1808]
**Describe the bug**
When I delete all tokens for a subject using `DELETE /oauth2/auth/sessions/consent` I get a correct 401 on the introspection endpoint. However when refreshing the deleted token it returns a 400. I expected a 401 so I can inform the user in the client that his session is no longer valid.

**Reproducing the bug**
1. Generate a token for a subject
2. Delete tokens for given subject using the `DELETE /oauth2/auth/sessions/consent` endpoint
3. Make an API call with the token retrieved in step 1
4. Observe 401 being returned
5. Attempt to refresh the token using the refresh_token retrieved in step 1
6. Observe 500 being returned

_Server logs_
```
time="2020-04-20T09:37:07Z" level=info msg="started handling request" method=DELETE remote="10.244.0.50:55216" request="/oauth2/auth/sessions/consent?subject=1A99513B-DC4C-4391-8A58-CFCB58A39009" request_id=6100baf9-f6ec-45a0-b62b-7d7da628aeac
time="2020-04-20T09:37:07Z" level=info msg="completed handling request" measure#hydra/admin: https://api.redacted.com/.latency=10224713 method=DELETE remote="10.244.0.50:55216" request="/oauth2/auth/sessions/consent?subject=1A99513B-DC4C-4391-8A58-CFCB58A39009" request_id=6100baf9-f6ec-45a0-b62b-7d7da628aeac status=204 text_status="No Content" took=10.224713ms
time="2020-04-20T09:37:10Z" level=info msg="started handling request" method=POST remote="10.244.0.106:37026" request=/oauth2/introspect
time="2020-04-20T09:37:10Z" level=error msg="An error occurred" debug=": not_found" description="The request could not be authorized" error=request_unauthorized hint="Check that you provided valid credentials in the right format."
time="2020-04-20T09:37:10Z" level=info msg="completed handling request" measure#hydra/admin: https://api.redacted.com/.latency=6539685 method=POST remote="10.244.0.106:37026" request=/oauth2/introspect status=200 text_status=OK took=6.539685ms
time="2020-04-20T09:37:11Z" level=info msg="started handling request" method=POST remote="10.244.0.95:53658" request=/oauth2/token request_id=d2d424e8-4e89-4b30-96d7-ce7a1548b972
time="2020-04-20T09:37:11Z" level=error msg="An error occurred" debug=": not_found" description="The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed" error=invalid_request hint="Make sure that the various parameters are correct, be aware of case sensitivity and trim your parameters. Make sure that the client you are using has exactly whitelisted the redirect_uri you specified."
time="2020-04-20T09:37:11Z" level=info msg="completed handling request" measure#hydra/public: https://api.redacted.com/.latency=5529558 method=POST remote="10.244.0.95:53658" request=/oauth2/token request_id=d2d424e8-4e89-4b30-96d7-ce7a1548b972 status=400 text_status="Bad Request" took=5.529558ms
```

_Server configuration_

Hydra:
```yaml
hydra:
  autoMigrate: true
  config:
    dsn: redacted
    urls:
      self:
        issuer: https://api.redacted.com/
      login: https://api.redacted.com/auth/login/
      consent: https://api.redacted.com/auth/consent/
service:
  public:
    annotations:
      getambassador.io/config: |
        ---
        apiVersion: ambassador/v1
        kind:  Mapping
        name:  hydra-public-mapping
        prefix: /oauth2/
        service: hydra-public:4444
        rewrite: /oauth2/
```
Oathkeeper:
```yaml
service:
  proxy:
    enabled: false

image:
  tag: v0.35.5

oathkeeper:
  config:
    authenticators:
      anonymous:
        enabled: true
        config:
          subject: guest
      oauth2_introspection:
        enabled: true
        config:
          introspection_url: http://hydra-admin:4445/oauth2/introspect
          scope_strategy: hierarchic
          introspection_request_headers:
            x-forwarded-proto: https
    authorizers:
      allow:
        enabled: true
    mutators:
      noop:
        enabled: true
      header:
        enabled: true
        config:
          headers:
            X-User: "{{ print .Subject }}"
```

**Expected behavior**
After deleting the tokens for a subject I expect all subsequent requests with previously distributed tokens for that subject to yield a 401 response so the clients can take appropriate actions.

**Environment**
- Version: v1.3.2_oryOS.17 (deployed using helm)
- Environment: Digital ocean kubernetes cluster

**Additional context**
Request from the client to refresh the token that returned a 401:
`POST https://api.redacted.com/oauth2/token`
```
client_id=redacted&grant_type=refresh_token&refresh_token=fcKJWu-F-lxoyOPb2LqX0P_ZF6V2nn1il_OK6NToRNg.wVz2nBzOXU0nbMPFZMwvXxKSPC_dxEtqkkEu8oFM3xU&client_secret=
```
