### ISSUE TITLE
Invalid ttl.refresh_token -1 (no expiration)

### ISSUE THREAD

**Issue by Aterocana** [ory/hydra#1811]
**Describe the bug**

Setting `ttl.refresh_token` to `-1` doesn't work as expected.
[Docs](https://www.ory.sh/hydra/docs/reference/configuration) state: `Configures how long refresh tokens are valid. Set to -1 for refresh tokens to never expire`

**Reproducing the bug**

I used [this docker image](https://hub.docker.com/layers/oryd/hydra/v1.4.6-alpine/images/sha256-4c8d80c66f01fef48bf4110f7dbbd741b1df8a3f9818a8ae929badbbe060ce2b?context=explore), with a configuration file with this `ttl` section:

```yml
ttl:
  login_consent_request: 1h
  access_token: 1h
  refresh_token: -1
  id_token: 1h
  auth_code: 10m
```

Using a refresh token expiration works as expected, for example with this `ttl` section:
```yml
ttl:
  login_consent_request: 1h
  access_token: 1h
  refresh_token: 720h
  id_token: 1h
  auth_code: 10m
```

Here's a complete configuration:
```yml
log:
  level: debug
  format: json

serve:
  public:
    port: 4444
    cors:
      enabled: true
      allowed_origins:
        - https://*
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type
      allow_credentials: true
      max_age: 10
      debug: true
    access_log:
      disable_for_health: false

  admin:
    port: 4445
    cors:
      enabled: true
      allowed_origins:
        - https://*
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type
      allow_credentials: true
      max_age: 10
      debug: true

    access_log:
      disable_for_health: false

dsn: mysql://DATABASE_URL?parseTime=true

oidc:
  subject_identifiers:
    enabled:
      - pairwise
      - public
    pairwise:
      salt: some-random-salt

  dynamic_client_registration:
    default_scope:
      - openid
      - offline
      - offline_access

urls:
  self:
    issuer: https://OUR_DOMAIN
    public: https://OUR_DOMAIN
  login: https://OUR_DOMAIN/login
  consent: https://OUR_DOMAIN/consent
  logout: https://OUR_DOMAIN/logout
  error: https://OUR_DOMAIN/error
  post_logout_redirect: https://OUR_DOMAIN

strategies:
  scope: DEPRECATED_HIERARCHICAL_SCOPE_STRATEGY

ttl:
  login_consent_request: 1h
  access_token: 1h
  refresh_token: 720h
  id_token: 1h
  auth_code: 10m

oauth2:
  expose_internal_errors: true
  hashers:
    bcrypt:   
      cost: 10

secrets:
  system:
    - SECRET
  cookie:
    - COOKIE

profiling: cpu 
profiling: mem  
```

And here's logs:
```
{"[config_key=ttl.refresh_token]":"doesn't validate with \"#/definitions/duration\"","config_file":"/config/config.yml","level":"fatal","msg":"The configuration is invalid and could not be loaded.","time":"2020-04-22T05:57:54Z"}
```

**Expected behavior**

The configuration should be OK, and refresh tokens should have no expiration.

**Environment**

Hydra 1.4.6 with [this docker image](https://hub.docker.com/layers/oryd/hydra/v1.4.6-alpine/images/sha256-4c8d80c66f01fef48bf4110f7dbbd741b1df8a3f9818a8ae929badbbe060ce2b?context=explore), run as docker container.

**Additional Context**

The TLS part is omitted because it's handled by a NGINX server before hydra.

**Comment by aeneasr** [comment]
I believe the correct notation would be `-1ns` which represents `-1` in duration time. Could you try if that works for you? If so, we'll probably have to fix that by either allowing `-1` or making it explicit that it needs to be `-1ns`

**Comment by Aterocana** [comment]
same problem with this configuration:
```yml
log:
  level: debug
  format: json

serve:
  public:
    port: 4444
    cors:
      enabled: true
      allowed_origins:
        - https://*
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type
      allow_credentials: true
      max_age: 10
      debug: true
    access_log:
      disable_for_health: false

  admin:
    port: 4445
    cors:
      enabled: true
      allowed_origins:
        - https://*
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type
      allow_credentials: true
      max_age: 10
      debug: true

    access_log:
      disable_for_health: false

dsn: mysql://DATABASE_URL?parseTime=true

oidc:
  subject_identifiers:
    enabled:
      - pairwise
      - public
    pairwise:
      salt: some-random-salt

  dynamic_client_registration:
    default_scope:
      - openid
      - offline
      - offline_access

urls:
  self:
    issuer: https://OUR_DOMAIN
    public: https://OUR_DOMAIN
  login: https://OUR_DOMAIN/login
  consent: https://OUR_DOMAIN/consent
  logout: https://OUR_DOMAIN/logout
  error: https://OUR_DOMAIN/error
  post_logout_redirect: https://OUR_DOMAIN

strategies:
  scope: DEPRECATED_HIERARCHICAL_SCOPE_STRATEGY

ttl:
  login_consent_request: 1h
  access_token: 1h
#  refresh_token: 720h
  refresh_token: -1ns
  id_token: 1h
  auth_code: 10m

oauth2:
  expose_internal_errors: true
  hashers:
    bcrypt:   
      cost: 10

secrets:
  system:
    - SECRET
  cookie:
    - COOKIE

profiling: cpu 
profiling: mem  
```

I got this in the logs:
```json
{"[config_key=ttl.refresh_token]":"doesn't validate with \"#/definitions/duration\"","config_file":"/config/config.yml","level":"fatal","msg":"The configuration is invalid and could not be loaded.","time":"2020-04-23T14:06:26Z"}
```

Is that what you mean? Thanks for help.
