### ISSUE TITLE
/userinfo endpoint misses www-authenticate header for 401 response

### ISSUE THREAD

**Issue by mikapfl** [ory/hydra#1827]
Hi,

the [/userinfo API endpoint](https://www.ory.sh/hydra/docs/reference/api/#openid-connect-userinfo) returns a `401 Unauthorized` Response when the token is not correct, but does not send a `WWW-Authenticate` header.
According to [the spec for 401 Unauthorized](https://tools.ietf.org/html/rfc7235#section-3.1), a server MUST send a `WWW-Authenticate` header when generating a `401 Unauthorized` response.

Unfortunately, several OIDC resource provider libraries like for example mozilla-django-oidc require the `WWW-Authenticate` header (see for example https://github.com/mozilla/mozilla-django-oidc/blob/master/mozilla_django_oidc/contrib/drf.py#L80).
Therefore, it would be good if Hydra would send a `WWW-Authenticate` header as required by the spec.

1. Run hydra.
2. Make API Request to hydra's `/userinfo` endpoint with any invlaid token, for example `curl -i -H 'Authorization: bearer XXX' http://127.0.0.1:4444/userinfo`
3. Request fails with this output:
```
HTTP/1.1 401 Unauthorized
Content-Type: application/json
Date: Fri, 24 Apr 2020 14:04:11 GMT
Content-Length: 231

{"error":"request_unauthorized","error_description":"The request could not be authorized","error_hint":"Check that you provided valid credentials in the right format.","status_code":401,"error_debug":": not_found","request_id":""}
```
However, it should also contain a `WWW-Authenticate` header.

_Server logs_
```
INFO[0154] started handling request                      method=GET remote="127.0.0.1:41164" request=/userinfo
ERRO[0154] An error occurred while handling a request    code=401 debug= details="map[]" error=request_unauthorized reason="Check that you provided valid credentials in the right format." request-id= status=401 writer=JSON
INFO[0154] completed handling request                    measure#hydra/public: http://127.0.0.1:4444/.latency=252096 method=GET remote="127.0.0.1:41164" request=/userinfo status=401 text_status=Unauthorized took="252.096µs"
```

_Server configuration_

```yaml
# config for test servers
log:
  level: info

serve:
  public:
    port: 4444
    host: 127.0.0.1
    access_log:
      disable_for_health: false
  admin:
    port: 4445
    host: 127.0.0.1
    access_log:
      disable_for_health: false

dsn: memory
oauth2:
  expose_internal_errors: true
```

**Expected behavior**

In every error response with the error code `401 Unauthorized` a `WWW-Authenticate` header should be sent.

**Environment**

- Version: v1.4.2+oryOS.18
- Environment: Debian
