### ISSUE TITLE
tracing provider - jaeger doesn't work with v1.5.1

### ISSUE THREAD

**Issue by yuekun0707** [ory/hydra#1917]
I'm trying to run the [v1.5.1](https://github.com/ory/hydra/archive/v1.5.1.tar.gz) and build it by `CGO_ENABLED=0 GO111MODULE=on GOOS=linux GOARCH=amd64 go build`. Then make a alpine docker image with my .hydra.yaml. The tracing part is :
```
# ORY Hydra supports distributed tracing.
tracing:
  provider: jaeger
  service_name: ORY Hydra
  providers:
    jaeger:
      local_agent_address: 127.0.0.1:6831
      propagation: jaeger
      sampling:
        type: const
        value: 1
        server_url: http://localhost:5778/sampling
```
Run the docker image on CentOS machine, and the OAuth service is ok (client credentials request and authorization code request are ok).  I can also see the log information `msg=Jaeger tracer configured!` from the `ory-hydra-example--hydra` job.

I run a jaeger all-in-one on the same machine. yml file is 
```
jaeger:
  image: jaegertracing/all-in-one:1.7.0
  ports:
  - "5775:5775/udp"
  - "6831:6831/udp"
  - "6832:6832/udp"
  - "5778:5778"
  - "16686:16686"
  - "14268:14268"
  - "9411:9411"
```
from the jaeger UI, I can not see the traces from hydra service. Is there something wrong I did?
There is no more log about jaeger after `ory-hydra-example--hydra` start but `msg=Jaeger tracer configured!`
I also try the [HotROD](https://www.jaegertracing.io/docs/1.18/getting-started/#sample-app-hotrod) demo in the same machine and it works well, I can see the traces in jaeger UI.

Also I find the log in json format don't work too. I set the format to `json` in the .hydra.yaml file, but the log is still text format, like this:
```
time=2020-06-19T06:35:17Z level=info msg=Jaeger tracer configured! audience=application service_name=ORY Hydra service_version=
```

**Comment by aeneasr** [comment]
I assume that you've made some requests?

**Comment by aeneasr** [comment]
Sorry, I didn't see the part - it appears that you've made requests! I'll look into it, maybe there's something funny going on :)

**Comment by yuekun0707** [comment]
Thanks for your attention ~
I can't make the jaeger part work, there is no log output, so I don't know the reason. I also try the `v1.5.0-beta.5` and `v1.5.0-beta.1`, still not work.

**Comment by aeneasr** [comment]
I've checked out if this works in the quickstart and I was not able to reproduce this issue. Here is what I did:

```
$ docker-compose -f quickstart.yml -f quickstart-postgres.yml -f quickstart-tracing.yml up
```

Then I made a mock request to Hydra:

```
$ curl 'http://127.0.0.1:4444/oauth2/auth?client_id=i-do–not-exist'
```

And was able to see the trace in Jaeger:

<img width="1392" alt="Bildschirmfoto 2020-06-22 um 11 59 30" src="https://user-images.githubusercontent.com/3372410/85274937-eab81400-b47f-11ea-8dee-97acc914c8ef.png">

Maybe you can use this as a basis.

**Comment by yuekun0707** [comment]
Thank you very much, I try this "5 Minute Tutorial" and it works well. I will find out why my job can not get the traces. If there is something new, I will update it here.

**Comment by yuekun0707** [comment]
@aeneasr  hi, I find the reason. In the config file: 
```
# ORY Hydra supports distributed tracing.
tracing:
  provider: jaeger
  service_name: ORY Hydra
  providers:
    jaeger:
      local_agent_address: 127.0.0.1:6831
      propagation: jaeger
      sampling:
        type: const
        value: 1
        server_url: http://localhost:5778/sampling
```
When I change the `127.0.0.1` and `localhost` to the Intranet IP address(like 10.*.*.*), the jaeger is ok. I will find why.
