### ISSUE TITLE
Jaeger local_agent_address dont support hostname:port

### ISSUE THREAD

**Issue by cotocisternas** [ory/hydra#1956]
**Describe the bug**

Configuration validation does not support jaeger agent being a hostname or fqdn

**Reproducing the bug**

export TRACING_PROVIDERS_JAEGER_LOCAL_AGENT_ADDRESS=jaeger.local:6831

_Server logs_

```
tracing.providers.jaeger.local_agent_address: jaeger.local:6831
                                              ^-- does not match pattern "^\\[(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))]:([0-9]*)$"

tracing.providers.jaeger.local_agent_address: jaeger.local:6831
                                              ^-- does not match pattern "^([0-9]{1,3}\\.){3}[0-9]{1,3}:([0-9]*)$"

time=2020-07-19T00:29:41Z level=fatal msg=The services failed to start because the configuration is invalid. Check the output above for more details. audience=application service_name= service_version=
```

_Server configuration_

```yaml
tracing:
  provider: jaeger
  service_name: ory-hydra
  providers:
    jaeger:
      local_agent_address: jaeger.local:6831
      propagation: jaeger
      sampling:
        type: const
        value: 1
        server_url: http://jaeger.local:5778/sampling
```

**Expected behavior**

Accept and resolve the hostname or fqdn

**Environment**

- Version: v1.5.2, 4d2cd48ee6e43175331febc8463159204b5ae40b
- Environment: Docker, ...

**Additional context**
