### ISSUE TITLE
Split HTTPS handling for public/admin

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#1962]
**Is your feature request related to a problem? Please describe.**

When deploying ORY Hydra to prod/stage/..., the admin endpoint is typically inwards facing (internal network) and the public endpoint is usually exposed behind a LoadBalancer that does TLS termination.

The admin endpoint may or may not be secured using HTTPS (e.g. mTLS when using Istio/Linkerd/...) but since the traffic is only internal (e.g. checking if a token is valid) it should be up to the deployment team to decide if that traffic is encrypted or not (using e.g. mTLS).

Several pieces - for example ORY Oathkeeper - require some tricky configuration to get `X-Forwarded-Proto` with the right value working while not adding any actual security to the process.

Similarly, disabling strict SSL verification to work around this is also not very useful as it would make it easy to MITM traffic within the internal network.

**Describe the solution you'd like**

In general, the idea to enforce HTTPs really comes from "no external internet traffic should be able to hit ORY Hydra without being TLS traffic". This however shouldn't make it painful for devs/ops to deploy the stack and use it in their own infrastructure.

I currently lack ideas of how to solve it, but the idea of this issue is to start a discussion and come up with the best possible solution.

**Additional context**

I wanted to link all the issues that have been opened because of this but will do so at a later stage.

**Comment by aeneasr** [comment]
https://smallstep.com/certificates/

**Comment by Gibheer** [comment]
Would it make sense to introduce a new namespace into the config named listener which configures different listeners with their options, like the address, port, tls options and subdirectories?
Then in each serve option one could reference these listeners to attach to.

```
listener:
  default:
    host: 0.0.0.0
    port: 443
    tls:
      private_key: file.priv
      certificate: file.crt
      chain: file.crt
  admin:
    host: 127.0.0.1
    port: 10001
    auth_header: USER_AUTH
  unix_sock:
    host: /var/run/hydra.sock

serve:
  public:
    listener: default
  admin:
    listener: unix_sock
# or make it inline?
#  admin:
#    listener:
#      host: 127.0.0.1
#      port: 8080
# or use the same listener for both endpoints
#   admin:
#     listener:
#       use: default
#       path: "/admin"
#       tls: ...
```

Internally the handling could be done by implementing instantiating the http server in the required version and attaching the routes to that server. The http server can use different prepared net.Listener, so these could be prepared in advance.
