### ISSUE TITLE
[HELP] The OAuth 2.0 Client is not allowed to request scope "email"

### ISSUE THREAD

**Issue by mzch** [ory/hydra#2016]
**Describe the bug**

I tried to sign up Hydra via [Coral](https://github.com/coralproject/talk), but an error occurred. Please help me to fix this issue.

**Reproducing the bug**

1. Run hydra
2. Add client by `hydra clients create...`
3. Set up OpenID Connect in Coral
4. Try to sign up from Coral
5. Request fails with 'The requested scope is invalid, unknown, or malformed'

_Server logs_

```
Aug 24 17:26:19 n21 hydra[23936]: time=2020-08-24T17:26:19-07:00 level=error msg=An error occurred audience=application error=map[message:invalid_scope reason:The OAuth 2.0 Client is not allowed to request scope "email". status:Bad Request status_code:400] http_request=map[headers:map[accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9 accept-encoding:gzip, deflate, br accept-language:ja,en-US;q=0.9,en;q=0.8 user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36 x-forwarded-for:118.243.18.144 x-forwarded-proto:https] host:authern.com method:GET path:/oauth2/auth query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:@ scheme:http] service_name= service_version=```
```

_Server configuration_

```yaml
## ORY Hydra Configuration
#

## log ##
#
# Configures the logger
#
log:
  level: debug
  format: text

## serve ##
#
# Controls the configuration for the http(s) daemon(s).
#
serve:

  public:
    cors:
      enabled: true
      allowed_origins:
        - https://authern.com
        - https://*.authern.com
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type
      allow_credentials: true
      options_passthrough: false
      max_age: 86400
      debug: false
    host: unix:/srv/hydra/run/public.sock
    socket:
      mode: 511

  admin:
    cors:
      enabled: true
      allowed_origins:
        - https://authern.com
        - https://*.authern.com
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type
      allow_credentials: true
      options_passthrough: false
      max_age: 86400
      debug: false
    host: unix:/srv/hydra/run/admin.sock
    socket:
      mode: 511

  tls:
    allow_termination_from:
      - 127.0.0.1/32
      - 192.168.207.0/24

  cookies:
    same_site_mode: Strict
    same_site_legacy_workaround: false

## dsn ##
#
# Sets the data source name. This configures the backend where ORY Hydra persists data. If dsn is "memory", data will be written to memory and is lost when you restart this instance. ORY Hydra supports popular SQL databases. For more detailed configuration information go to: https://www.ory.sh/docs/hydra/dependencies-environment#sql
#
dsn: postgres://hydra:password@localhost/hydra?sslmode=disable

## webfinger ##
#
# Configures ./well-known/ settings.
#
webfinger:

  jwks:

    broadcast_keys:
      - hydra.openid.id-token

  oidc_discovery:
    client_registration_url: https://admin.authern.com/clients
    supported_claims:
      - email
      - username
    supported_scope:
      - email
      - whatever
      - read.photos
    userinfo_url: https://authern.com/userinfo

## oidc ##
#
# Configures OpenID Connect features.
#
oidc:

  subject_identifiers:
    enabled:
      - public
      - pairwise
    pairwise:
      salt: xxx

  dynamic_client_registration:
    default_scope:
      - openid
      - offline
      - offline_access

## urls ##
#
urls:

  self:
    issuer: https://authern.com/
    public: https://authern.com/

  login: https://authern.com/login
  consent: https://authern.com/consent
  logout: https://authern.com/logout
  error: https://authern.com/error
  post_logout_redirect: https://authern.com/logout-successful

## strategies ##
#
strategies:

  scope: exact
  access_token: opaque

## ttl ##
#
# Configures time to live.
#
ttl:

  login_consent_request: 1h
  access_token: 1h
  refresh_token: 720h
  id_token: 1h
  auth_code: 10m

## oauth2 ##
#
oauth2:

  expose_internal_errors: false
  hashers:
    bcrypt:
      cost: 15
  pkce:
    enforced: true
    enforced_for_public_clients: true

## secrets ##
#
# The secrets section configures secrets used for encryption and signing of several systems. All secrets can be rotated, for more information on this topic go to: https://www.ory.sh/docs/hydra/advanced#rotation-of-hmac-token-signing-and-database-and-cookie-encryption-keys
#
secrets:

  system:
    - xxx
  cookie:
    - xxx
## profiling ##
#
# Enables profiling if set. For more details on profiling, head over to: https://blog.golang.org/profiling-go-programs
#
profiling: cpu
```

**Expected behavior**

Successfully sign up.

**Environment**

- Version: v1.7.0
- Environment: Debian 10.5

**Additional context**
