### ISSUE TITLE
Hydra doesn't start after updating to the latest tag (v1.9.0-alpha)

### ISSUE THREAD

**Issue by and-semakin** [ory/hydra#2138]
**Describe the bug**

Previously it worked fine in my development environment, but it seems like the new release has broken something.

**Reproducing the bug**

My `docker-compose.yaml` config:

```
version: '3.7'
services:
  hydra:
    image: oryd/hydra:latest
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
    command:
      serve all --dangerous-force-http
    environment:
      - URLS_SELF_ISSUER=http://127.0.0.1:4444
      - DSN=memory
      - SECRETS_SYSTEM=secret_goes_here
```

If you pin the version to `v1.8.5` it starts and works, but with the `latest` tag I get the following output:

```
$ docker-compose logs -f hydra
Attaching to hydra
hydra         | Config file not found because "Config File ".hydra" Not Found in "[/]""
hydra         | 2020/10/20 16:49:29 error: Config File ".hydra" Not Found in "[/]"
hydra         | time=2020-10-20T16:49:29Z level=fatal msg=Unable to instantiate service registry. audience=application error=map[message:no driver is capable of handling the given DSN] service_name= service_version=
hydra exited with code 1
```

**Expected behavior**

Hydra starts and works. Or there is some kind of migration plan or some mention of breaking changes in [CHANGELOG](https://github.com/ory/hydra/blob/master/CHANGELOG.md#190-alpha1-2020-10-20).

**Environment**

- Version: v1.9.0-alpha
- Environment: Docker
