### ISSUE TITLE
Configuration is not recognized by certain docker containers

### ISSUE THREAD

**Issue by szigya** [ory/hydra#2164]
**Describe the bug**

Docker doesn't recognize DSN=memory or at least fails to run with it if I use oryd/hydra:v1.9 as base, but it works if I use oryd/hydra:v1.9-sqlite.

**Reproducing the bug**

0. docker image prune -a -f && docker system prune -a -f
1. docker build --no-cache -t registry.gitlab.com/.../.../sso:$TAG . 
2. docker-compose --env-file .env.dev up
3. Hydra container exits with 1 (unless I use other image like v1.9-sqlite )

_Server logs_

```
sso_1                  | time=2020-11-04T08:41:11Z level=fatal msg=Unable to instantiate service registry. func=github.com/ory/hydra/driver.NewDefaultDriver file=/home/ory/driver/driver_default.go:22 audience=application error=map[message:no driver is capable of handling the given DSN trace:
sso_1                  | github.com/ory/hydra/driver.NewRegistry
sso_1                  |        /home/ory/driver/registry.go:69
sso_1                  | github.com/ory/hydra/driver.NewDefaultDriver
sso_1                  |        /home/ory/driver/driver_default.go:20
sso_1                  | github.com/ory/hydra/cmd/server.RunServeAll.func1
sso_1                  |        /home/ory/cmd/server/handler.go:155
sso_1                  | github.com/spf13/cobra.(*Command).execute
sso_1                  |        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846
sso_1                  | github.com/spf13/cobra.(*Command).ExecuteC
sso_1                  |        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
sso_1                  | github.com/spf13/cobra.(*Command).Execute
sso_1                  |        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
sso_1                  | github.com/ory/hydra/cmd.Execute
sso_1                  |        /home/ory/cmd/root.go:57
sso_1                  | main.main
sso_1                  |        /home/ory/main.go:33
sso_1                  | runtime.main
sso_1                  |        /usr/local/go/src/runtime/proc.go:204
sso_1                  | runtime.goexit
sso_1                  |        /usr/local/go/src/runtime/asm_amd64.s:1374] service_name= service_version=

```

_Server configuration_

hydra.yml

```yaml
# see http://github.com/ory/hydra/blob/master/docs/docs/reference/configuration.md
log:
  level: trace
dsn: memory
serve:
  admin:
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:8080
        - http://localhost:4444
        - http://localhost:4200
        - http://sso
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
      exposed_headers:
        - Content-Type
  public:
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:8080
        - http://localhost:4444
        - http://localhost:4200
        - http://sso
        - http://localhost
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
      exposed_headers:
        - Content-Type

```

Dockerfile

```
FROM oryd/hydra:v1.9

COPY hydra.yml /home/ory/.hydra
COPY hydra.yml /.hydra

EXPOSE 4444 4445 5555
```

docker-compose
```yaml
 sso:
    hostname: sso
    image: registry.gitlab.com/certum-tech/atsy/sso:${HYDRA_TAG}
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve all --dangerous-force-http
    environment:
      - URLS_SELF_ISSUER=${SSO_URL}
      - URLS_CONSENT=${AUTH_BASE_URL}/auth/consent
      - URLS_LOGIN=${AUTH_BASE_URL}/auth/login
      - URLS_LOGOUT=${AUTH_BASE_URL}/auth/logout
      - DSN=memory
    restart: unless-stopped

  hydra-create-client:
    image: oryd/hydra:v1.9 #Should be the same as in sso's Dockerfile
    depends_on:
      - sso
    command: clients create --endpoint http://sso:4445 --id atsy-ui --token-endpoint-auth-method none --callbacks "${APP_BASE_URL},${AUTH_BASE_URL},${AUTH_BASE_URL}/silent_renew.html,${AUTH_BASE_URL}/.well-known/openid-configuration"

```

.env.dev
```
HYDRA_TAG=feature-fix-hydra
TAG=feature-fix-hydra
SSO_URL=http://localhost:4444
AUTH_BASE_URL=http://localhost:8080
APP_BASE_URL=http://localhost:4200
```

**Expected behavior**

Hydra should start

**Environment**

- Version: v1.9
- Environment: Ubuntu
Docker version 19.03.13, build 4484c46d9d
docker-compose version 1.25.0, build unknown

This behaviour is really strange and I am struggling with missing CORS headers as well even if hydra is running.
