### ISSUE TITLE
Postgres broken pipe regression

### ISSUE THREAD

**Issue by jfyne** [ory/hydra#2312]
**Describe the bug**

I think the bug described here https://github.com/ory/hydra/issues/1599 and fixed by moving to https://github.com/jackc/pgx is back. After upgrading to `v1.9` we have started seeing a lot of broken pipe errors. This could be due to the move to https://github.com/gobuffalo/pop ?

**Reproducing the bug**

1. Wait some period of time for connections to go stale
2. Make a request to `/oauth2/auth/requests/login` with the login challenge
3. Request fails with response: `The error is unrecognizable StatusCode:0`, underlying error is `write: broken pipe`

_Server logs_

```
level=error msg=An error occurred while handling a request audience=application error=map[message:couldn't start a new transaction: could not create new transaction: write failed: write tcp x.x.x.x:35838->x.x.x.x:5432: write: broken pipe] http_request=map[headers:map[accept:application/json accept-encoding:gzip user-agent:Go-http-client/1.1 x-forwarded-proto:http x-request-id:3e43ac9a-24a2-490b-92ff-20629939a8dc] host:prod-hydra:4445 method:GET path:/oauth2/auth/requests/login query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:127.0.0.1:54926 scheme:http] http_response=map[status_code:500] service_name=ORY Hydra service_version=v1.9.0
```

_Server configuration_

```yaml
  - name: hydra-config
    literals:
      - URLS_SELF_ISSUER=https://xxx/
      - URLS_SELF_PUBLIC=https://xxx/
      - URLS_LOGIN=https://xxxlogin/
      - URLS_CONSENT=https://xxx/login/consent
      - URLS_LOGOUT=https://xxx/login/logout
      - URLS_ERROR=http://xxx/login/error
      - SECRETS_SYSTEM=xxx
      - SECRETS_COOKIE=xxx
      - SERVE_PUBLIC_CORS_ENABLED=true
      - SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=https://*.xxx,https://*.xxx
      - SERVE_TLS_ALLOW_TERMINATION_FROM=127.0.0.1/32
      - HYDRA_ADMIN_URL="http://localhost:4445"
      - LOG_LEVEL=warn
      - DSN=postgres://xxx:xxx@xxx/xxx?sslmode=disable
```

**Expected behavior**

In `v1.8` we did not have any broken pipes. Prior to that pre `jackc/pgx` we experienced the broken pipe errors.

**Environment**

- Version: v1.9.0, git sha hash 7120b4f5d038f065df4fa80d7dbbb8aa8bd0b987
- Environment:  oryd/hyda:v1.9.0, on GKE
