### ISSUE TITLE
/verison endpoint does not return current service version

### ISSUE THREAD

**Issue by haomingyin** [ory/hydra#2337]
**Describe the bug**

/version endpoint doesn't return service version even though the version has been set in environment variables as `VERSION=v1.9.2`

**Reproducing the bug**

Start up with docker-compose file.
```
version: "3.9"
services:
  postgres:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hydra
    ports:
      - "5432:5432"

  hydra-migrate:
    image: oryd/hydra:v1.9.2-alpine
    depends_on:
      - postgres
    environment:
      - SECRETS_SYSTEM=abcdefghijklmn1234567890
      - DSN=postgres://postgres:password@postgres:5432/hydra?sslmode=disable
    command: migrate sql -e --yes
    restart: on-failure

  hydra:
    image: oryd/hydra:v1.9.2-alpine
    depends_on:
      - postgres
      - hydra-migrate
    environment:
      - SECRETS_SYSTEM=abcdefghijklmn1234567890
      - DSN=postgres://postgres:password@postgres:5432/hydra?sslmode=disable
      - SERVE_ADMIN_HOST=0.0.0.0
      - SERVE_PUBLIC_HOST=0.0.0.0
      - URLS_SELF_PUBLIC=http://localhost:4444/
      - URLS_SELF_ISSUER=http://localhost:4444/
      - URLS_CONSENT=http://localhost:8000/api/v1/auth/consent
      - URLS_LOGIN=http://localhost:8000/api/v1/auth/login
      - VERSION=v1.9.2
      - LOG_LEAK_SENSITIVE_VALUES=true
    ports:
      - "4444:4444"
      - "4445:4445"
    command: serve all --dangerous-force-http

```

Pass the `VERSION=v1.9.2` environment variable for docker. The endpoint `/version` returns 
```
{ "version": "" }
```

Tested for both envrionment and config file. Both of them do not work.

_Server logs_

```
time=2021-02-03T08:03:30Z level=info msg=completed handling request http_request=map[headers:map[accept:application/json accept-encoding:gzip, deflate, br user-agent:PostmanRuntime/7.26.10 x-forwarded-proto:http] host:localhost:4445 method:GET path:/version query:<nil> remote:172.21.0.1:56812 scheme:http] http_response=map[status:200 text_status:OK took:173.864µs]
```

_Server configuration_

```yaml
version: v1.9.2
```

**Expected behavior**
It should return the version with the JSON blob returned.

**Environment**

- Version: v1.9.2
- Environment: Docker,
