### ISSUE TITLE
Response code 404 not defined in swagger spec for /oauth2/revoke

### ISSUE THREAD

**Issue by Crevil** [ory/hydra#2350]
**Describe the bug**

Thank you for a great project and documentation. I ran into a bug (I think) while playing with the 5 minute tutorial.

When revoking an access token that is not found the hydra server returns a 404 response but this is not a defined response in the swagger specification. This leads to an error like `response status code does not match any response statuses defined for this endpoint` instead of just indicating that the token was not found (or whatever makes sense to disclose security wise).

**Reproducing the bug**

Start hydra

```
$ git clone https://github.com/ory/hydra.git
$ cd hydra

# start hydra
$ docker-compose -f quickstart.yml \
    -f quickstart-postgres.yml \
    up --build
```

In a new terminal revoke any fake token value.
```
$ docker-compose -f quickstart.yml exec hydra \
  hydra token revoke \
    --endpoint http://127.0.0.1:4445/ \
    --client-id my-client \
    --client-secret secret \
    a-value
The request failed with the following error message:
response status code does not match any response statuses defined for this endpoint in the swagger spec (status 404): {resp:0xc000932090}
```

_Server logs_

```
hydra_1          | time=2021-02-11T10:48:07Z level=info msg=started handling request http_request=map[headers:map[accept:application/json accept-encoding:gzip authorization:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". user-agent:Go-http-client/1.1] host:127.0.0.1:4445 method:POST path:/oauth2/revoke query:<nil> remote:127.0.0.1:34420 scheme:http]
hydra_1          | time=2021-02-11T10:48:07Z level=info msg=completed handling request http_request=map[headers:map[accept:application/json accept-encoding:gzip authorization:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". user-agent:Go-http-client/1.1] host:127.0.0.1:4445 method:POST path:/oauth2/revoke query:<nil> remote:127.0.0.1:34420 scheme:http] http_response=map[status:404 text_status:Not Found took:176.4µs]
```

_Server configuration_

From `contrib/quickstart/5-min/hydra.yml`

```yaml
serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://127.0.0.1:4444
  consent: http://127.0.0.1:3000/consent
  login: http://127.0.0.1:3000/login
  logout: http://127.0.0.1:3000/logout

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
```

**Expected behavior**

Expected no error but instead just an acknowledgement of the revocation.

**Environment**

- Version:
```
$ docker-compose -f quickstart.yml exec hydra \
  hydra version
Version:    v1.9.2
Git Hash:   f0580e2581e202ec7299f45822db37228228aee9
Build Time: 2021-01-29T15:02:55Z
```
- Environment: Docker on maxOS
