### ISSUE TITLE
REST API Token Introspection Endpoint - request_unauthorized (401)

### ISSUE THREAD

**Issue by jfarleyx** [ory/hydra#2401]
**Describe the bug**
When calling the REST API's token introspection endpoint, passing it a JWT access token acquired via the client-credential flow, I receive the following error message: 
```
level=info 
msg=access denied 
audience=application 
error=map[debug:not_found 
message:request_unauthorized 
reason:Check that you provided valid credentials in the right format. 
status:Unauthorized 
status_code:401] 
http_request=map[
headers:map[accept:application/json 
accept-encoding:gzip 
authorization:Basic <redacted base64 encoded client_id:client_secret>
user-agent:Go-http-client/1.1 
x-forwarded-for:<redacted> 
x-forwarded-proto:https] 
host:<redacted>.cloud 
method:POST 
path:/oauth2/introspect 
query:<nil> 
remote:192.168.14.218:38133 
scheme:http] 
service_name=ORY Hydra 
service_version=v1.9.2
```

I can take the same access token that generated the response above and perform token introspection using the CLI without any issue. 

The client is configured to use the default "client_secret_basic" auth method (see client settings below). In the Authorization header of the request I provide the client_id:client_secret as a base64 encoded (UTF-8) string. e.g. 

```
Authorization Basic <base64 UTF-8 encoded client_id:client_secret>
```

In the body of the request I provide the following: 
```
token: <my access token>
scope: offline_access
```

I've tried with and without "scope" in the body. **The same scope was used to request the token.**

client info:
```json
{
	"audience": [
		"http://localhost:8081/",
		"http://localhost:8081/cb"
	],
	"client_id": "<redacted client id>",
	"client_name": "Test",
	"created_at": "2021-03-10T13:56:58.000Z",
	"grant_types": [
		"authorization_code",
		"client_credentials"
	],
	"jwks": {},
	"metadata": {},
	"post_logout_redirect_uris": [
		"http://localhost:8081/"
	],
	"redirect_uris": [
		"http://localhost:8081/cb"
	],
	"response_types": [
		"code",
		"id_token",
                "token"
	],
	"scope": "openid offline_access email profile",
	"subject_type": "public",
	"token_endpoint_auth_method": "client_secret_basic",
	"updated_at": "2021-03-10T13:56:58.000Z",
	"userinfo_signed_response_alg": "none"
}
```

I have repeatedly verified that the client id and secret are correct and were encoded correctly. Perhaps I'm overlooking a requirement for calling the introspection endpoint. I've reviewed the documentation multiple times and I'm just not seeing what I am doing wrong. I could use some advice on what to try next to get this to work. 

I expect to call the token introspection REST endpoint, passing it the client creds via the header, and get a response without error. While the error does state that the request was unauthorized and that I should verify the credentials are in the right format, as far as I can tell my credentials are correct and in the right format: base64 UTF-8 encoded client_id:client_secret. 

**Reproducing the bug**

We're running Ory Hydra in K8S, fronted by an NGINX API Gateway. The gateway validates tokens by calling the token introspection endpoint. 

NGINX will perform the call to Hydra's token introspection endpoint. Here is what the request looks like in NGINX:
```
proxy_method POST;
proxy_set_header Content-Type "application/x-www-form-urlencoded";
proxy_set_header Accept "application/json";
proxy_set_header Authorization "Basic <redacted base64 encoded client_id:client_secret>";
proxy_set_body "token:$http_token scope:offline_access";
proxy_pass https://<redacted>.cloud/oauth2/introspect;
```
TLS is terminated at a load balancer, prior to the request getting to the Hydra container.

Steps:
1. Get a JWT access token from Hydra via Golang's client credential flow library
2. Call /oauth2/introspect REST endpoint to validate token with the following info: 
```
Content-Type application/x-www-form-urlencoded
Accept application/json
Authorization Basic <base64 UTF-8 encoded client_id:client_secret>
Body: 
  token: <access token>
  scope: offline_access
Path: <hydra admin api URL>/oauth2/introspect
```
Call fails. 
3. Perform introspection via CLI for same token and it works. 

_Server logs_

error from log is above

_Server configuration_

```yaml
hydra:
  # The ORY Hydra configuration. For a full list of available settings, check:
  # https://www.ory.sh/hydra/docs/reference/configuration/
  config:
    serve:
      public:
        port: 4444
      admin:
        port: 4445
      tls:
        allow_termination_from:
          - 172.16.0.0/16
          - 192.168.0.0/16
    secrets: {}
    secretAnnotations:
    # Create the secret before installation, and only then. This saves the secret from regenerating during an upgrade
      helm.sh/hook: "pre-install"
      helm.sh/hook-delete-policy: "before-hook-creation"
    # Use a pre-existing secret (see secret.yaml for required fields)
    existingSecret: my-secret
    strategies:
      access_token: jwt

    autoMigrate: false
    dangerousForceHttp: false
    dangerousAllowInsecureRedirectUrls: false

tracing:
    datadog:
      enabled: false

maester:
  enabled: true
```

All other settings are default. 

We're using an AWS Aurora v2.09.2 (MySQL v5.7) for DSN. 
We're using AWS Load Balancers to terminate TLS with an ACM cert, rather than the ingress originally included in the Hydra Helm chart. 

**Expected behavior**

I expect to call the token introspection endpoint passing it the client creds via the header and get a response without error.

**Environment**

- Version: v1.9.2 (same issue occurred on 1.8.5, too)
- Environment: K8S (EKS)

**Additional context**

I am able to get a token without issue and verify the token via the CLI, but the REST endpoint doesn't work.
