### ISSUE TITLE
Readiness/Liveness probe fail, when dangerous-force-http ist not set (Kubernetes)

### ISSUE THREAD

**Issue by robinmanuelthiel** [ory/hydra#2403]
**Describe the bug**

When deploying version `v1.9.2` to Kubernetes without adding `--dangerous-force-http` to the pod args, the Pod never comes up and stays Unhealthy due to failing probes. When port-forwarding the service, this can be confirmed, as calling `/health/ready` returns an `500: Client sent an HTTP request to an HTTPS server.` error.

**Reproducing the bug**

1. Deploy `oryd/hydra:v1.9.2` with readiness and liveness probes to a Kubernetes cluster without `--dangerous-force-http` 
2. See, that the Pod won't come up
3. Remove readiness and liveness probes and deploy again
4. Port forward  `kubectl port-forward svc/ory-hydra 4445:4445`
5. Get an error with `curl localhost:4445`

_Server logs_

```
$ kubectl describe pod ...

Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  22s               default-scheduler  Successfully assigned orytest/ory-hydra-589d4bc644-kwp5j to aks-worker-18347077-vmss000002
  Normal   Pulled     21s               kubelet            Container image "oryd/hydra:v1.9.2" already present on machine
  Normal   Created    21s               kubelet            Created container ory-hydra-migrate
  Normal   Started    21s               kubelet            Started container ory-hydra-migrate
  Normal   Pulled     18s               kubelet            Container image "oryd/hydra:v1.9.2" already present on machine
  Normal   Created    18s               kubelet            Created container ory-hydra
  Normal   Started    18s               kubelet            Started container ory-hydra
  Warning  Unhealthy  7s                kubelet            Readiness probe failed: HTTP probe failed with statuscode: 400
  Warning  Unhealthy  4s (x2 over 14s)  kubelet            Liveness probe failed: HTTP probe failed with statuscode: 400
```

_Server configuration_

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ory-hydra
spec:
  selector:
    matchLabels:
      app: ory-hydra
  template:
    metadata:
      labels:
        app: ory-hydra
    spec:
      containers:
      - name: ory-hydra
        image: oryd/hydra:v1.9.2
        command: ["hydra"]
        args: ["serve", "-c", "/etc/config/hydra.yaml", "all", "--dangerous-force-http"] # <- required for readiness probe to work
        env:
        - name: DSN
          value: postgres://... # Deleted for this issue
        - name: OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT
          value: deletedforthisissue
        - name: SECRETS_SYSTEM
          value: deletedforthisissue
        volumeMounts:
        - name: hydra-config
          mountPath: /etc/config
          readOnly: true
        ports:
        - name: public
          containerPort: 4444
        - name: admin
          containerPort: 4445
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/alive
            port: admin
        readinessProbe:
          httpGet:
            path: /health/ready
            port: admin
      initContainers:
      - name: ory-hydra-migrate
        image: oryd/hydra:v1.9.2
        command: ["hydra"]
        args: ["migrate", "-c", "/etc/config/hydra.yaml", "sql", "-e", "--yes"]
        env:
        - name: DSN
          value: postgres://... # Deleted for this issue
        - name: OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT
          value: deletedforthisissue
        - name: SECRETS_SYSTEM
          value: deletedforthisissue
        volumeMounts:
        - name: hydra-config
          mountPath: /etc/config
          readOnly: true
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: hydra-config
        configMap:
          name: hydra-config
---
apiVersion: v1
kind: Service
metadata:
  name: ory-hydra
spec:
  type: ClusterIP
  selector:
    app: ory-hydra
  ports:
    - port: 4444
      targetPort: public
      name: public
    - port: 4445
      targetPort: admin
      name: admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra-config
data:
  "hydra.yaml": |
    urls:
      self:
        issuer: https://test.removed.com
      consent: https://test.removed.com
      login: https://test.removed.com
      logout: https://test.removed.com
      post_logout_redirect: https://test.removed.com
    strategies:
      access_token: jwt
    oidc:
      subject_identifiers:
        supported_types:
          - pairwise
          - public
```

**Expected behavior**

The readiness probes should still be accessible even without `--dangerous-force-http`

**Environment**

- Version: v1.9.2
- Environment: Kubernetes, Docker, ...

**Comment by Demonsthere** [comment]
Hello there,
I think a simple solution would be to modify the probe definition and add the scheme to it:
```yaml
livenessProbe:
          httpGet:
            path: /health/alive
            port: admin
            scheme: HTTPS
```
