### ISSUE TITLE
May we make the Jaeger configuration maxTagValueLength be configureable ?

### ISSUE THREAD

**Issue by kobayashilin** [ory/hydra#2447]
**Is your feature request related to a problem? Please describe.**

May we make the Jaeger configuration maxTagValueLength be configureable for [ory/x/tracing tracer.go](https://github.com/ory/x/blob/master/tracing/tracer.go) ? 
The default length 256 isn't enough for we observe the query.

**Describe the solution you'd like**

Configuration in yaml like

```
tracing:
  service_name: ory/hydra
  provider: jaeger
  providers:
    jaeger:
      propagation: jaeger
      max_tag_value_length: 10240
```
**max_tag_value_length: 10240**

Thank you!

Best Regards,

Yan-Ting
