### ISSUE TITLE
TTL: 1 second difference

### ISSUE THREAD

**Issue by TVenuMadhav** [ory/hydra#2507]
**Describe the bug**
---

If we set the configuration ttl.access_token as 1h , the token.expiry_at should be 3600 but comes to be 3599. There is a 1 second difference. (Same for all other configurations like 2h, 10h etc)

**Reproducing the bug**
---

I am currently running a containerized instance using  `oryd/hydra:v1.9.0-alpine` image along with `postgres` db container.

The configuration for `ttl.access_token` is set to `1h` (which is also the default)
Reference :- https://www.ory.sh/hydra/docs/reference/configuration/

Here is the docker compose file:

```
version: '3'
services:
    db:
        image: postgres:10.6
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: hydrauser
            POSTGRES_DB: hydradb
            POSTGRES_PASSWORD: hydrapass

    db-migrate:
        build:
            context: .
        image: my-hydra
        links:
            - db
        depends_on:
            - db
        restart: on-failure
        environment: 
            DSN: postgres://hydrauser:hydrapass@db:5432/hydradb?sslmode=disable
        command: migrate sql -ye

    auth-service:
        image: my-hydra
        ports:
            - "9000:4444"
            - "9001:4445"
        links:
            - db
        depends_on:
            - db-migrate
        restart: on-failure
        environment: 
            DSN: postgres://hydrauser:hydrapass@db:5432/hydradb?sslmode=disable
            SECRETS_SYSTEM: somesecretthatislongenough
            URLS_SELF_ISSUER: https://localhost:9000/
            URLS_CONSENT: http://localhost:9020/consent
            URLS_LOGIN: http://localhost:9020/login
        command: serve all
```

Here is the custom docker file
```
FROM oryd/hydra:v1.9.0-alpine

# Hydra configuration
COPY hydra.yaml /home/ory/.hydra.yaml
```

The sample hydra configuration `hydra.yaml`
```
ttl:
   access_token: 1h
```
Steps:

1. I created a hydra client using admin api

```
curl --location --request POST 'https://localhost:9001/clients' \
--header 'Content-Type: application/json' \

--data-raw '{
    "client_id": "1",
    "client_secret": "1234567",
    "grant_types": [
        "client_credentials"
    ],
    "token_endpoint_auth_method": "client_secret_post",
    "owner": "lol",
    "metadata": "{}",
    "redirect_uris": []
}'
```

2. and, made a request to the token endpoint for the client that was created,

```
curl --location --request POST 'https://localhost:9000/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Accept:  application/json' \
--data-urlencode 'client_id=1' \
--data-urlencode 'client_secret=1234567' \
--data-urlencode 'grant_type=client_credentials'
```
3. Got back the response:
```
{
    "access_token": "6rP900Si8lvenNScE9oKzjhtZCEPtkKdVXaTKhTwL44.yiN8R9lGdahDYjirWbaxa06PzcybKbKO05UpSLGw72s",
    "expires_in": 3599,
    "scope": "",
    "token_type": "bearer"
}

```

3. Here the token `expires_in` is supposed to be `3600` (1 hour) instead of `3599`

_Originally posted by @TVenuMadhav in https://github.com/ory/hydra/discussions/2449#discussioncomment-587740_

_Server configuration_

The sample hydra configuration `hydra.yaml`
```yaml
ttl:
   access_token: 1h
```
**Expected behavior**
---

Token 200 response with `expires_in` set to `3600`
```
{
    "access_token": "6rP900Si8lvenNScE9oKzjhtZCEPtkKdVXaTKhTwL44.yiN8R9lGdahDYjirWbaxa06PzcybKbKO05UpSLGw72s",
    "expires_in": 3600,
    "scope": "",
    "token_type": "bearer"
}
```

**Environment**
---
 Docker

**Additional context**
---
This issue was raised after discussions and clarifications in Q&A -> https://github.com/ory/hydra/discussions/2449
