### ISSUE TITLE
Space character in secret.system value

### ISSUE THREAD

**Issue by nurzhan86** [ory/hydra#2609]
**Describe the bug**

Version 1.9 and above.
Whitespace is not defined as a character in secret.system value.

We use hydra 1.8.5 in k8s cluster, and we want to upgrade it to latest 1.10.2 version.
It so happened that the current system.secret value contains a string with space characters, for example: "abc 12345 678 9 def 987654".
And hydra 1.8.5 works great with that, no errors during or after install.

But when we trying to upgrade hydra to version 1.10.2, the error:
"The configuration contains values or keys which are invalid"

**Reproducing the bug**

1.Try to install hydra 1.10.2 with secret.system value like: "abc 12345 678 9 def 987654"

_Server logs_

```
The configuration contains values or keys which are invalid:
secrets: map[cookie:[[abc 12345 678 9 def 98765]] system:[[abc 12345 678 9 def 98765]]]
^-- validation failed

The configuration contains values or keys which are invalid:
secrets.system: [[abc 12345 678 9 def 98765]]
^-- validation failed

The configuration contains values or keys which are invalid:
secrets.system.0: [abc
^-- length must be >= 16, but got 4

The configuration contains values or keys which are invalid:
secrets.system.1: 12345
^-- length must be >= 16, but got 5

The configuration contains values or keys which are invalid:
secrets.system.2: 678
^-- length must be >= 16, but got 3
```
...
and so on... 

_Server configuration_

**values.yaml:**
```yaml
replicaCount: 1

image:
  repository: oryd/hydra
  tag: v1.10.2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  public:
    enabled: true
    type: ClusterIP
    port: 4444
    annotations: {}
    labels: {}
  
  admin:
    enabled: true
    type: ClusterIP
    port: 4445
    annotations: {}
    labels: {}

ingress:
  public:
    enabled: false
    annotations: {}
    hosts:
      - host: public.hydra.localhost
        paths: ["/"]

  admin:
    enabled: false
    annotations: {}
    hosts:
      - host: admin.hydra.localhost
        paths: ["/"]

hydra:
  config:
    serve:
      public:
        port: 4444
      admin:
        port: 4445
      tls:
        allow_termination_from:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
    secrets:
      system:
        - abc 12345 678 9 def 98765
    secretAnnotations:
      helm.sh/hook: "pre-install"
      helm.sh/hook-delete-policy: "before-hook-creation"
    urls:
      self: {}

  autoMigrate: false
  dangerousForceHttp: false
  dangerousAllowInsecureRedirectUrls: false

deployment:
  resources: {}

  securityContext: 
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 100
    allowPrivilegeEscalation: false
    privileged: false

  lifecycle: {}

  labels: {}

  annotations: {}

  nodeSelector: {}

  extraEnv: []

  tracing:
    datadog:
      enabled: false

  tolerations: []

  extraVolumes: []
  extraVolumeMounts: []

  autoscaling:
    enabled: false

  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 5
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 5

  automountServiceAccountToken: false

job:
  annotations: {}

affinity: {}

maester:
  enabled: false

hydra-maester:
  adminService: {}
```

**Expected behavior**

hydra deployed and running

**Environment**

- Version: v1.10.2
- Environment: Centos, Docker, Kubernetes

**Additional context**

Hydra 1.10.2 think that my current system.secret value is a multi-value secret and there are all less 16 length, but in version 1.8.5 it is a single value and works fine.

How to tell to hydra 1.10.2 to work with space character contained value in system.secret?
How to upgrade hydra to version 1.10.2 with current system.secret value containing space characters?

[EDIT: ADDED CODE BLOCKS]

**Comment by zepatrik** [comment]
This looks like a code bug that we have to fix. Currently there seems no way to apply a workaround, sorry for that.

**Comment by aeneasr** [comment]
The bug is probably in here: https://github.com/ory/x/tree/master/configx

If you have any idea or trace - contribs are highly appreciated!

**Comment by nurzhan86** [comment]
Is it possible to migrate db from one secret key to another (without whitespace)?
Any migration scripts or tutorial? What hash method used and what tables and columns must be?

**Comment by vinckr** [comment]
Did you see this guide @nurzhan86: [Secrets and Key Rotation](https://www.ory.sh/hydra/docs/next/guides/secrets-key-rotation/)?

**Comment by nurzhan86** [comment]
> Did you see this guide @nurzhan86: [Secrets and Key Rotation](https://www.ory.sh/hydra/docs/next/guides/secrets-key-rotation/)?

Yes, but there is an information about adding new secret, not replace old with new
It was a question how to replace old secret with new (and re-encrypt old data with new secret), because old secret is not compatible with hydra new version because of bug in new version of hydra.

**Comment by zepatrik** [comment]
Sorry, we will have to fix the code first because you can't replace secrets, only add new ones. Until then you will have to stay on the old version, but be assured that we are prioritizing this issue.

**Comment by zepatrik** [comment]
Just to make sure, you are deploying hydra using our helm charts right? I think that results in `secrets.system` being exposed as env vars. Which in turn is probably the problematic part, because parsing a string array form env vars supposedly splits at spaces. Can you verify this is happening?
In that case it should be possible to work around the issue by ensuring the `secrets.system` are read form a config yaml instead. Not sure on the exact steps of how to achieve that with our helm charts though, maybe @Demonsthere has an idea?

**Comment by nurzhan86** [comment]
> Just to make sure, you are deploying hydra using our helm charts right? I think that results in `secrets.system` being exposed as env vars. Which in turn is probably the problematic part, because parsing a string array form env vars supposedly splits at spaces. Can you verify this is happening?
> In that case it should be possible to work around the issue by ensuring the `secrets.system` are read form a config yaml instead. Not sure on the exact steps of how to achieve that with our helm charts though, maybe @Demonsthere has an idea?

Yes, we are deploying hydra using helm chart.
Yes, `secrets.system` being exposed as env vars, I checked it by running hydra without k8s, just by docker-compose and env in it.
**And YES, it works** (secret with whitespaces) when I pass the secret.system from config.yaml, it works with version 1.10.2, but it is necessary that ENV system.secret must not be set, because it overrides values from config.yaml.
And now the problem (as you said) how to pass it to k8s, because after deploying it by helm chart, the system.secret ENV is not optional (optional: false) and it must be set.
But it is some steps to resolve my task to upgrade hydra, thank you @zepatrik 
If you have any idea how to pass secret in config yaml with helm chart and turn off it in ENV, it will be very good :)

**Comment by Demonsthere** [comment]
Hello there @nurzhan86, I've done some testing and was able to install hydra with the following setup:

```yaml
hydra:
  autoMigrate: true
  dangerousForceHttp: true
  config:
    dsn: "postgres://ory:ory@postgresql.default.svc.cluster.local/ory?sslmode=disable&max_conn_lifetime=10s"
    secrets:
      system: "foo bar 123 456 lorem"
maester:
  enabled: false
```

However, this format results in an error:

```yaml
hydra:
  autoMigrate: true
  dangerousForceHttp: true
  config:
    dsn: "postgres://ory:ory@postgresql.default.svc.cluster.local/ory?sslmode=disable&max_conn_lifetime=10s"
    secrets:
      system:
        - "foo bar 123 456 lorem 1"
        - "foo bar 123 456 lorem 2"
        - "foo bar 123 456 lorem 3"
maester:
  enabled: false
```

Could you verify if this is the same for you?
