### ISSUE TITLE
Migrate to OAS3.0

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#2913]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Ory Kratos is already using the OpenAPI 3.0 specification by using the Ory CLI migration command.

### Describe your ideal solution

We should migrate to OAS 3.0 as well here. In particular we need security definitions:

```
- op: add
  path: /components/securitySchemes/oauth2RegistrationAccessToken
  value:
    scheme: bearer
    type: http
```

### Workarounds or alternatives

None

### Version

master
