### ISSUE TITLE
Hydra JWT - invalid Signature

### ISSUE THREAD

**Issue by 0Tom2020** [ory/hydra#3051]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hello!

I have set up a complete new instance of hydra (5 min tutorial of ory) with jwt strategy. 
When I request a new token, I get a token that does not have a valid signature, according to jwt.io.

Header according to jwt.io:
{
  "alg": "RS256",
  "kid": "public:046d1671-c0bc-46bb-bdd8-2d8fa08dabe9",
  "typ": "JWT"
}

--> invalid Sugnature.

If I set the algorithm to HS256 on jwt.io, the signature is valid. What do I have to configure to make the jwt header fit?

### Reproducing the bug

1. I used the compose file of the ory 5 min tutorial with my given configuration.
2. Fetched sucessfully new token (.../oauth2/token)
3. copied token to jwt.io 

### Relevant configuration

```yml
urls:
  self:
    issuer: ...
  consent: ...
  login: ...
  logout: ...
strategies:
  access_token: jwt

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - public
```

### Version

1.11.7

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose
