### ISSUE TITLE
`revocation_endpoint` and `end_session_endpoint`

### ISSUE THREAD

**Issue by carloschida** [ory/hydra#3162]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

This is the missing use case in #2708.

My front end app (https://my-app.sh) which handles hydra and kratos, is a Next.js app — this is only for context though, it could happen with any other kind.

In its rewrites (proxy redirects), I have something like this:
```json
[
  {
        source: '/.well-known/:path*',
        destination: 'https://hydra-public.sh/.well-known/:path*',
      },
      {
        source: '/openid/admin/:path*',
        destination: 'http://hydra-admin.sh/:path*',
      },
      {
        source: '/openid/token/:path*',
        destination: 'http://hydra-token.sh/:path*',
      },
      {
        source: '/openid/:path*',
        destination: 'http://hydra-public/:path*',
      },
]
```

With this rewrites, I manage to have my back-end (hydra/kratos) and my front-end in the same domain so that the cookies are valid everywhere.

Then, with this excerpt of my config:
```yaml
webfinger:
  oidc_discovery:
    token_url: https://my-app.sh/openid/token/oauth2/token
    auth_url: https://my-app.sh/openid/oauth2/auth
    jwks_url: https://my-app.sh/.well-known/jwks.json
    
urls:
  login: '' # Irrelevant
  consent: '' # Irrelevant
  logout: '' # Irrelevant
  error: '' # Irrelevant
  post_logout_redirect: '' # Irrelevant
  self:
    public: https://my-app.sh/openid
    issuer: https://my-app.sh
```

I get the following results in `https://my-app.sh/.well-known/openid-configuration`:
```json5
{
  "issuer": "https://my-app.sh/", // ✅
  "authorization_endpoint": "https://my-app.sh/openid/oauth2/auth", // ✅
  "token_endpoint": "https://my-app.sh/openid/token/oauth2/token", // ✅
  "jwks_uri": "https://my-app.sh/.well-known/jwks.json", // ✅
  // ...
  "userinfo_endpoint": "https://my-app.sh/openid/userinfo", // ✅
  //...
  revocation_endpoint": "https://my-app.sh/oauth2/revoke", // ❌ It should be https://my-app.sh/openid/oauth2/revoke
  // ...
  end_session_endpoint": "https://my-app.sh/oauth2/sessions/logout" // ❌ It should be https://my-app.sh/openid/oauth2/sessions/logout
   // ...
}
```

The error seems to come from here: https://github.com/ory/hydra/blob/22e1ebb5742477e924ebac83c711bec08bffd7ba/oauth2/handler.go#L230-L259

It says:
```go
RevocationEndpoint:                     urlx.AppendPaths(h.c.IssuerURL(), RevocationPath).String(),
// ...
EndSessionEndpoint:                     urlx.AppendPaths(h.c.IssuerURL(), LogoutPath).String(),
```

Or am I getting something wrong?

### Reproducing the bug

Copy the config and run.
See `/.well-known/openid-configuration`.

### Version

v1.11.7

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker
