### ISSUE TITLE
nginx - Connection reset by peer

### ISSUE THREAD

**Issue by marvinville** [ory/hydra#3322]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

This documentation: https://www.ory.sh/docs/hydra/self-hosted/deploy-hydra-example does not give the expected result.

### Reproducing the bug

Follow this documentation as it is

https://www.ory.sh/docs/hydra/self-hosted/deploy-hydra-example

### Relevant log output

```shell
2022/10/27 01:24:49 [error] 3017452#3017452: *2732 readv() failed (104: Connection reset by peer) while reading upstream, client: 136.158.83.131, server: sso.sunwatt.io, request: "GET /health?secret=CHANGE-ME-INSECURE-PASSWORD HTTP/1.1", upstream: "http://127.0.0.1:4445/health?secret=CHANGE-ME-INSECURE-PASSWORD", host: "sso.sunwatt.io"
```

### Relevant configuration

```yml
serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://127.0.0.1:4444
  consent: http://127.0.0.1:3000/consent
  login: http://127.0.0.1:3000/login
  logout: http://127.0.0.1:3000/logout

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis

dsn: postgres://hydra:Minski1234@127.0.0.1:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
urls:
  self:
    issuer: https://sso.sunwatt.io


log:
  level: debug
  format: text
  leak_sensitive_values: true
```

### Version

v1.11.10

### On which operating system are you observing this issue?

Linux
