### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:4445

### ISSUE THREAD

**Issue by DaveSmithh** [ory/hydra#3335]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

After deploying the code(ORY hydra docker v2.0.1) when accessing the APIs from browser or postman getting I am getting error- 
request- `curl --location --request GET 'https://some_domain/clients'`
`Error: connect ECONNREFUSED 127.0.0.1:4445`

But the other APIs like health, key and version APIs are working fine from browser

### Reproducing the bug

Steps-
1. Run - `sudo docker-compose -f quickstart.yml -f quickstart-postgres.yml up  --build -d`
2.  Run- `curl --location --request GET 'https://openid.video.wiki/clients'`

### Relevant log output

```shell
hydra_1          | time=2022-11-03T07:24:29Z level=info msg=started handling request http_request=map[headers:map[accept:*/* accept-encoding:gzip, deflate, br connection:close postman-token:cc9214a3-2d3f-45f3-82ce-76cfbef211f9 user-agent:PostmanRuntime/7.26.8 x-forwarded-for:157.36.130.56] host:some_host method:GET path:/clients query:<nil> remote:172.20.0.1:39892 scheme:http]
hydra_1          | time=2022-11-03T07:24:29Z level=info msg=completed handling request http_request=map[headers:map[accept:*/* accept-encoding:gzip, deflate, br connection:close postman-token:cc9214a3-2d3f-45f3-82ce-76cfbef211f9 user-agent:PostmanRuntime/7.26.8 x-forwarded-for:157.36.130.56] host:some_host method:GET path:/clients query:<nil> remote:172.20.0.1:39892 scheme:http] http_response=map[headers:map[cache-control:private, no-cache, no-store, must-revalidate content-type:text/html; charset=utf-8 location:http://localhost:4445/admin/clients] size:71 status:307 text_status:Temporary Redirect took:1.025308ms]
```

### Version

v2.0.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by DaveSmithh** [comment]
I managed to avoid this issue by downgrading to v1.9.1 but on latest version this bug remains.

**Comment by aeneasr** [comment]
From the Changelog:

> Administrative endpoints now have an /admin prefix (e.g. POST /admin/clients). Existing administrative endpoints will redirect to this new prefixed path for backwards compatibility.

If Hydra is not configured correctly, the redirect can end up in a scenario where you end up at the wrong port, causing the bug you observe.

**Comment by TroutZen** [comment]
Hi

Hi @aeneasr. I am also seeing this and currently blocked performing an update from 1.x to 2.x. Trying to debug it, but having a difficult time. Can you clarify what might not be configured incorrectly? Our configuration from 1.x only changed marginally, so a bit confused what could be causing the redirect to localhost.

Hoping to perform this upgrade, bc I heard the logging improves > 1.8, as part of another bug investigation.

These were the only changes we made:

```
secret:
  enabled: false
  nameOverride: "redacted"
  secretAnnotations:
    helm.sh/hook-weight: "0"
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
    helm.sh/resource-policy: "keep"
  hashSumEnabled: true

hydra:
  config:
    dsn: "gets_error_when_this_is_blank" # K8s was erroring when this was empty, saying it could not be blank
    urls:
      self:
        issuer: https://redacted.com/ # added a trailing slash here...

  automigration:
    enabled: false
    type: job
    customCommand: []
    customArgs: []
```
