### ISSUE TITLE
Add min/max and supported cypher suite TLS configuration in admin/public interfaces

### ISSUE THREAD

**Issue by aarmam** [ory/hydra#3412]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We would like to have an option to configure min/max supported TLS version and cipher suites for both the admin and public interfaces.

### Describe your ideal solution

Introduce configurable MinVersion, MaxVersion and CipherSuites options in [server handler tls configuration](https://github.com/ory/hydra/blob/master/cmd/server/handler.go#L320).

Sample configuration:

```yaml
serve.public.tls.min_version: tls13
serve.public.tls.max_version: tls13
serve.public.tls.cipher_suites: TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384
serve.admin.tls.min_version: tls13
serve.admin.tls.max_version: tls13
serve.admin.tls.cipher_suites: TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384
```

### Version

2.x

### Additional Context

Willing to help implementing it if necessary!
