### ISSUE TITLE
Cannot enable cors in ory hydra cloud

### ISSUE THREAD

**Issue by sirkrisp** [ory/hydra#3436]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Inspired by https://www.ory.sh/docs/hydra/guides/cors, I am trying to enable cors (set hydra_serve_public_cors_enabled to true) in my ory cloud project. However, while allowed_origins is successfully updated, hydra_serve_public_cors_enabled stays false.

### Reproducing the bug

Create a cloud project and apply oauth2-config.yaml

### Relevant configuration

```yml
serve:
  admin:
    cors:
      enabled: true
      allowed_origins:
        - "*"
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
      exposed_headers:
        - Content-Type
    tls:
      enabled: false
  public:
    cors:
      enabled: true
      allowed_origins:
        - "*"
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
      exposed_headers:
        - Content-Type
        - Access-Control-Allow-Origin
    tls:
      enabled: false
  tls:
    enabled: false
```

### Version

ory version is v0.2.2

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None
