### ISSUE TITLE
Health probes not being filtered

### ISSUE THREAD

**Issue by MrWolfZ** [ory/hydra#3521]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I run Hydra in Kubernetes installed via the helm chart. I have set both `serve.admin.request_log.disable_for_health` and `serve.public.request_log.disable_for_health` to `true`, but I still see log entries for `/health/ready` and `/health/alive`.

Here's the relevant excerpt from the config map:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra
  namespace: ory
  labels:
    "app.kubernetes.io/name": "hydra"
    "app.kubernetes.io/instance": "hydra"
    "app.kubernetes.io/version": "v2.1.1"
    "app.kubernetes.io/managed-by": "Helm"
    "helm.sh/chart": "hydra-0.33.1"
data:
  "hydra.yaml": |
    log:
      format: json
      level: info
    serve:
      admin:
        port: 4445
        request_log:
          disable_for_health: true
      public:
        port: 4444
        request_log:
          disable_for_health: true
```

### Reproducing the bug

1 . Deploy Hydra to Kubernetes via helm using the following values:

    ```yaml
    hydra:
      config:
        serve:
          public:
            request_log:
              disable_for_health: true

          admin:
            request_log:
              disable_for_health: true
    ```

2. Get the logs from the Hydra pod

### Relevant log output

```shell
{"http_request":{"headers":{"accept":"*/*","connection":"close","user-agent":"kube-probe/1.27"},"host":"127.0.0.1","method":"GET","path":"/health/ready","query":null,"remote":"10.200.20.65:38794","scheme":"http"},"level":"info","msg":"started handling request","time":"2023-05-20T15:54:51.933945842Z"}
{"http_request":{"headers":{"accept":"*/*","connection":"close","user-agent":"kube-probe/1.27"},"host":"127.0.0.1","method":"GET","path":"/health/alive","query":null,"remote":"10.200.20.65:38796","scheme":"http"},"level":"info","msg":"started handling request","time":"2023-05-20T15:54:51.936208645Z"}
{"http_request":{"headers":{"accept":"*/*","connection":"close","user-agent":"kube-probe/1.27"},"host":"127.0.0.1","method":"GET","path":"/health/ready","query":null,"remote":"10.200.20.65:38794","scheme":"http"},"http_response":{"headers":{"content-type":"application/json; charset=utf-8"},"size":16,"status":200,"text_status":"OK","took":2986423},"level":"info","msg":"completed handling request","time":"2023-05-20T15:54:51.937286816Z"}
{"http_request":{"headers":{"accept":"*/*","connection":"close","user-agent":"kube-probe/1.27"},"host":"127.0.0.1","method":"GET","path":"/health/alive","query":null,"remote":"10.200.20.65:38796","scheme":"http"},"http_response":{"headers":{"content-type":"application/json; charset=utf-8"},"size":16,"status":200,"text_status":"OK","took":3273882},"level":"info","msg":"completed handling request","time":"2023-05-20T15:54:51.939518026Z"}
```

### Relevant configuration

```yml
log:
  format: json
  level: info
serve:
  admin:
    port: 4445
    request_log:
      disable_for_health: true
  public:
    port: 4444
    request_log:
      disable_for_health: true
```

### Version

v2.1.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm
