### ISSUE TITLE
Client allowed cors origin didn't work

### ISSUE THREAD

**Issue by aomsin-api** [ory/hydra#3556]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hydra public client can't use allowed cors origin 

my hydra setting 

```yaml
serve:
  admin:
    cors:
      debug: true
      enabled: true
        - https://*.foo.com
      allow_credentials: true
  public:
    cors:
      enabled: true
      allowed_origins:
        - https://*.foo.com
      allow_credentials: true
```

hydra client

```json
{
  "allowed_cors_origin": ["https://bar.com"]
}
``` 

If I enter bar.com it should pass cors origin, but it's error said 
"Access to fetch at '{hydraserve}/oauth2/token' from origin 'https://bar.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource"
my hydra version is 1.11.9
admin go api version 1.11.8
public nodejs api version 1.11.8

### Reproducing the bug

Use helm install 

- hydra version 1.11.9
- create admin client with "allowed_cors_origin": "https://bar.com"
- enter https://bar.com
- hydra server blocked the post request from bar.com with cors error 

### Version

1.11.9

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm
