### ISSUE TITLE
Unexpected bug authenticating a valid client

### ISSUE THREAD

**Issue by juananinca** [ory/hydra#3581]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Recently I upgrade Hydra from 1.11.7 to 2.1.2 and migrate the db as well.
While I was testing the new release I noticed that one OAuth client was unable to authenticate, the rest of the clients were ok.
The only difference between the rest of the clients and that special client is that, that one has a longer client_secret and also it includes hyphens(-) and underscores (_).

When I try to authenticate the client I get an invalid_client error, but if try to authenticate the same client to the old hydra version with a backup of the db before the migration, then I'm able to authenticate it. So there is something wrong with the new version.

I tried to set THE SAME password for that client to the new version of service and it started working again.

It makes no sense to me.

### Reproducing the bug

Migrate from 1.11.7 to 2.1.2 with oauth client with special characters in the client secret.

### Version

2.1.2

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by aeneasr** [comment]
Hello, please provide a reproducible test case!

**Comment by juananinca** [comment]
I updated the ticket's section "Reproducing the bug" with a detailed steps to get the error I am facing.

**Comment by SzilardS** [comment]
@aeneasr I think this is caused by the hasherx module you guys have introduced in 2.x.
```
time=2024-01-31T14:18:08Z level=info msg=access denied audience=application error=map[debug:passwords are limited
to a maximum length of 72 characters message:invalid_client reason: stack_trace:
 github.com/ory/x/hasherx.init
     /go/pkg/mod/github.com/ory/x@v0.0.607/hasherx/hasher_bcrypt.go:16
```
I guess this check was not on the 1.x branch

**Comment by Vikash-novo** [comment]
I am also facing the same while after database migration from `v1.0.0-rc.6+oryOS.10 `-> `v2.2.0-rc.3`
Any updated/resolution on this or any workaround to get it resolved?

**Comment by MadisonEhlers-Vertex** [comment]
I too ran into this problem, and found that this was a pretty significant breaking change between hydra 1.x and 2.x, and yet I found very little documentation around this. The only documentation I found was on the [release notes for 2.0.0](https://github.com/ory/hydra/releases/tag/v2.0.0)
> Using BCrypt as the primary hashing algorithm for OAuth 2.0 Client Secrets creates excessive CPU consumption at scale. OAuth 2.0 Client Secrets are auto-generated in Ory Hydra 2.x, removing the need for excessive hashing costs.

I was able to reproduce this using docker and manual curl commands to create clients. 

### Setup Hydra Version 1.11.10
```yml
#docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: hydra
      POSTGRES_PASSWORD: hydra-password
      POSTGRES_DB: hydra
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hydra-migrate:
    # image: oryd/hydra:v2.3.0
    image: oryd/hydra:v1.11.10
    depends_on:
      - postgres
    environment:
      - DSN=postgres://hydra:hydra-password@postgres:5432/hydra?sslmode=disable
    command: migrate sql -e --yes

  hydra:
    # image: oryd/hydra:v2.3.0
    image: oryd/hydra:v1.11.10
    restart: always
    depends_on:
      - postgres
      - hydra-migrate
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
    environment:
      - DSN=postgres://hydra:hydra-password@postgres:5432/hydra?sslmode=disable
      - URLS_SELF_ISSUER=http://localhost:4444
      - URLS_CONSENT=http://localhost:3000/consent
      - URLS_LOGIN=http://localhost:3000/login
      - SECRETS_SYSTEM=someRandomSecretSystemYouShouldReplace
      - LOG_LEAK_SENSITIVE_VALUES=true
      - LOG_LEVEL=debug
    command:
      serve all --dangerous-force-http
      # serve all --dev

volumes:
  postgres_data:

```

Within the directory you saved your `docker-compose.yml` file in, run the following:
`docker-compose up --build`

### Create a client that has a secret of length > 72

```curl
curl --location 'http://localhost:4445/clients' \
--header 'Content-Type: application/json' \
--data '{
    "scope": "",
    "client_id": "my-client-id-abc",
    "client_name": "my test",
    "client_secret": "randomStringmLHgSZ41CzdB3jgDi8CZ5u6TyG6xMjzm99F2Zvx0a0vCVBDGEuNxMWPb1G2EtgtcmJB9Hn4W7",
    "token_endpoint_auth_method": "client_secret_basic",
    "grant_types": [
        "client_credentials"
    ]
}'
```

### Verify you can create an access token with the oauth2 client
```curl
curl --location '0.0.0.0:4444/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic bXktY2xpZW50LWlkLWFiYzpyYW5kb21TdHJpbmdtTEhnU1o0MUN6ZEIzamdEaThDWjV1NlR5RzZ4TWp6bTk5RjJadngwYTB2Q1ZCREdFdU54TVdQYjFHMkV0Z3RjbUpCOUhuNFc3' \
--data-urlencode 'grant_type=client_credentials'
```


## Upgrade To Hydra 2.X
Uncomment the lines in the yml file above so that the following are uncommented:
```yml
  hydra-migrate:
    image: oryd/hydra:v2.3.0
    # image: oryd/hydra:v1.11.10
  hydra:
    image: oryd/hydra:v2.3.0
    # image: oryd/hydra:v1.11.10

    command:
      # serve all --dangerous-force-http
      serve all --dev
```

Restart your server
`docker-compose up --build`


Try to reissue the token request
```curl
curl --location '0.0.0.0:4444/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic bXktY2xpZW50LWlkLWFiY2Q6cmFuZG9tU3RyaW5nbUxIZ1NaNDFDemRCM2pnRGk4Q1o1dTZUeUc2eE1qem05OUYyWnZ4MGEwdkNWQkRHRXVOeE1XUGIxRzJFdGd0Y21KQjlIbjRXNw==' \
--data-urlencode 'grant_type=client_credentials'
```

Only to observe that you get an exception:
```
{
    "error": "invalid_client",
    "error_description": "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)."
}
```

## Workaround - Truncate your secret _prior_ to sending it to hydra
One thing I found is that if you manually truncate your client_secret to 72 characters, your old truncated secret still works. So if I use `randomStringmLHgSZ41CzdB3jgDi8CZ5u6TyG6xMjzm99F2Zvx0a0vCVBDGEuNxMWPb1G2E` as my secret instead of `randomStringmLHgSZ41CzdB3jgDi8CZ5u6TyG6xMjzm99F2Zvx0a0vCVBDGEuNxMWPb1G2EtgtcmJB9Hn4W7`, I am able to successfully get a token:

```curl
curl --location '0.0.0.0:4444/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic bXktY2xpZW50LWlkLWFiYzpyYW5kb21TdHJpbmdtTEhnU1o0MUN6ZEIzamdEaThDWjV1NlR5RzZ4TWp6bTk5RjJadngwYTB2Q1ZCREdFdU54TVdQYjFHMkU=' \
--data-urlencode 'grant_type=client_credentials'
```

🎉  Access token! 🎉 
```
{"access_token":"ory_at_...}","expires_in":3599,"scope":"","token_type":"bearer"}%
```

### So from my understanding anyone using hydra that is setting secrets larger than 72 characters in version 1.x is forced to do one of the following:
1. Build a way via a proxy to pre-truncate any secret greater than 72 in length to be exactly 72 in length (😬 and I don't think this would be recommended...)
2. Update OAuth2 Clients to be truncated to some value less than or equal to 72 characters prior to migrating to 2.x

It's not clear to me at this time if there are other options, but these were the two options it seemed like I could find. Another thing that made this even more confusing is that hydra 2.x _still_ supports sending client secrets of length greater than 72, even though they very clearly break between the upgrade. So even though hydra is logging out an error for those same secrets after the upgrade, you can still recreate the same secret and have it work, as mentioned by @juananinca in the description.
 
Here is the debug error that is thrown after the upgrade to 2.x
```
msg=access denied audience=application error=map[debug:passwords are limited to a maximum length of 72 characters message:invalid_client
```

It would be ideal that oauth2 client creation would _fail_ with secrets greater than length 72, especially if the [bcrypt-secret-length has a known limit](https://www.ory.sh/docs/troubleshooting/bcrypt-secret-length)

While this is mostly a knowledge dump from me, I figured my findings may be beneficial to others, and it may be worth hearing from someone on they hydra team what they would think about the truncated secrets path, if that would be viable for developers stuck on this problem.
