### ISSUE TITLE
Would it make sense to build hydra statically

### ISSUE THREAD

**Issue by dereulenspiegel** [ory/hydra#374]
Currently I am building all my GoLang based services as a statically linked binary since they don't use CGo. I noticed that hydra isn't using CGo either. Building a statically linked binary allows to put hydra in docker container without any userland (so basically a scratch container). I think this is a quick and easy improvement.
For reference I tested building hydra with the following command `CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags="-s -w" -o hydra`

**Comment by arekkas** [comment]
Sounds good! We could probably provide an additional docker image flavor that uses this feature!

**Comment by arekkas** [comment]
According to [this article](http://blog.hashbangbash.com/2014/04/linking-golang-statically/) golang should do that automatically?

**Comment by arekkas** [comment]
Ah, it seems to have changed with Go 1.5. Do you know how this needs to be done with Go 1.7 / 1.8 @dereulenspiegel ?

**Comment by dereulenspiegel** [comment]
The command I posted in the initial ticket is a variant of the command how I currently build most of my service under Go 1.7. It creates statically linked binaries (as long as CGo isn't used) without problems and also strips debugging symbols (saving around 30% of the binary size).
I finally tried your official docker container and was a bit shocked that clocks in at several hundert MB. I think reducing image size is very welcome for many users.

**Comment by arekkas** [comment]
That is very likely caused by the base go image. Unfortunately, the 
alpine version doesn't work out of the box because we need git and 
mercurial for go get. The first step would to get hydra working on 
alpine. The hydra binary is (even with debugging symbols) only a few megs.


Am 13.02.2017 um 15:31 schrieb Till Klocke:

**Comment by dereulenspiegel** [comment]
You could also build the binary outside of docker and then just include it in an image derived from scratch. This way the image only about as big as the hydra binary. At least for many deployments this will be useful.
But the static binary should also run without problems on Alpine based images.

**Comment by arekkas** [comment]
Building it outside of docker is an option, however it would be kinda tricky with the CI toolchain right now because that works like this:

1. git tag (via github releases)
2. travis runs tests and builds binaries for github releases
3. on success, docker hub pulls code
4. docker hub builds image
5. done

If we build it outside, it would need to be like this:

1. git tag (via github releases)
2. travis runs tests and builds binaries for github releases
3. on success, travis builds docker image with the right binary
4. on success, travis pushes images to docker repo (can't be the same like right now because docker hub repository settings are *extremely* limited)
5. done

This however could be a bit error prone when a part of the CI toolchain fails and there's no easy way to restart only one piece of the chain.

Maybe preparing an alpine image that supports Go is *one* way to go, so basically install git, mercurial and go and be done with it. It would probably reduce the size significantly anyways. Squeezing out the last megs would then be a task for the future.

WDYT?

**Comment by michael-golfi** [comment]
I had a similar issue in the past with our own pipeline. We run a go server that connects to Hydra and is configured with the client id/secret for introspect.

I implemented the following pipeline for it (in gitlab):
1. Builds a static binary and caches it for remaining steps
2. Unit tests are run on the codebase
3. API tests are run on this cached binary (using Postman test specs). We build using Docker DinD (Docker inside Docker) then we push to our docker repo. 
4. Deploy to Kubernetes using a Docker-inside-Docker build.

The final result comes out to a 6 Mb static binary. The only issue is if you have to contact https urls then you also need to include ca-certificates in the Docker image.


```yaml
stages:
  - build
  - test
  - docker_build
  - deploy

Verify Build: 
  artifacts: 
    paths: 
      - assets/
      - vendor/
      - gatekeeper
    untracked: true
  except: 
    - tags
  image: "golang:1.7.4"
  script:
    - go get github.com/Masterminds/glide
    - glide install -v
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo --ldflags="-s" -o gatekeeper
  stage: build
  tags: 
    - golang

Unit Test:
  image: "golang:1.6.0"
  script:
    - go test -race -cover $(go list ./... | grep -v vendor)
  stage: test
  tags: 
    - golang

API Test:
  image: "uadevnet/docker-newman:latest"
  script:
    - sed -i -e "s/{{USERNAME}}/$USERNAME/g" assets/postman/tests.json
    - sed -i -e "s/{{PASSWORD}}/$PASSWORD/g" assets/postman/tests.json
    - mkdir -p /etc/ssl/certs
    - cp assets/ca-certificates.crt /etc/ssl/certs/
    - ./gatekeeper &
    - SERVER_PID=$!
    - sleep 10
    - /usr/bin/newman --collection="assets/postman/tests.json" --environment="assets/postman/environment.json"
    - kill $SERVER_PID
  stage: test
  tags:
    - golang
    
Build Image:
  image: "docker:latest"
  script:
    - docker build -t ${CI_PROJECT_NAME} . 2>&1 | tee build.log
    - ID=$(tail -1 build.log | awk '{print $3;}')
    - docker login --username="" --password="" $docker_repo
    - docker tag $ID "$docker_repo/${CI_PROJECT_NAME}:latest"
    - docker push "$docker_repo/${CI_PROJECT_NAME}:latest"
  services:
    - "docker:dind"
  only: 
    - master
  stage: docker_build

Deploy to SUT:
  variables:
    SPREAD_DIR: $CI_PROJECT_DIR/assets/kubernetes
    KUBECFG_SERVER: "https://kubernetes_server"
    KUBECFG_CERTIFICATE_AUTHORITY: /certs/kubernetes.ca.crt
    KUBECFG_CLIENT_CERTIFICATE: /certs/kubernetes.kubecfg.crt
    KUBECFG_CLIENT_KEY: /certs/kubernetes.kubecfg.key
    KUBECFG_TOKEN: $token
  stage: deploy
  image: redspreadapps/gitlabci
  only:
    - master
  script:
  - null-script
  tags:
    - kubedeploy
```

```Dockerfile
FROM scratch
MAINTAINER Michael Golfi <michael.m.golfi@gmail.com>
ADD gatekeeper /
# curl -o ca-certificates.crt https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt
ADD assets/ca-certificates.crt /etc/ssl/certs/
CMD [ "/gatekeeper" ]
EXPOSE 8080
```
