### ISSUE TITLE
Logout Not Working

### ISSUE THREAD

**Issue by emtammaru** [ory/hydra#3913]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

The quickstart configuration includes a logout config `logout: http://127.0.0.1:3000/logout`, and there's also a [logout page in the sample app ](https://github.com/ory/hydra-login-consent-node/blob/9d16da621f7f6b7008d88a1341e4bfd59141c615/src/routes/logout.ts) which are not working for me.  There's no logout button, so by looking in the API Reference docs I found the `oauth2/sessions/logout` endpoint.  It does not redirect to the configured logout page as would be expected to complete the logout challenge flow (`adminGetOAuth2LogoutRequest` followed by `adminAcceptOAuth2LogoutRequest`).  Am I missing something?  Looked through the source code, and I see it trying to redirect here: https://github.com/ory/hydra/blob/3a09db2abb978df91d875333b1eca70014cdcd10/consent/strategy_default.go#L878 But it's getting stuck somewhere?  Planning to debug it myself, but wanted to create an issue in case anyone else has experienced similar or else I'm simply missing some config.

### Reproducing the bug

1. Run 5 minute quick-start tutorial for self-hosting hydra (https://www.ory.sh/docs/hydra/5min-tutorial)
2. After logging in, navigate in the browser to `oauth2/sessions/logout`
3. Expected to be redirected to the logout page `http://127.0.0.1:3000/logout` to complete the logout flow but instead am redirected to default post logout URL.  

Screen recording of steps to reproduce below:
https://github.com/user-attachments/assets/6ef6dbbf-c5b5-4f65-b35d-e4d1b340d1af

### Relevant log output

```shell
The only error in the logs is:

hydra-1          | time=2024-12-19T19:57:30Z level=error msg=A request failed because configuration key "urls.post_logout_redirect" is missing or malformed. audience=application service_name=Ory Hydra service_version=v2.2.0
```
I tried setting the post_logout_redirect config, and it does redirect there.  However, it still never redirects to http://127.0.0.1:3000/logout with a logout challenge.
```


### Relevant configuration

```yml
serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://127.0.0.1:4444
  consent: http://127.0.0.1:3000/consent
  login: http://127.0.0.1:3000/login
  logout: http://127.0.0.1:3000/logout

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
```

### Version

v2.2 and master

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

None
