### ISSUE TITLE
Image publishing to DockerHub is misconfigured

### ISSUE THREAD

**Issue by polarathene** [ory/hydra#3917]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

Presently (_probably since the introduction of GoReleaser for this task?_) the DockerHub image registry has:
- Redundant single platform tags still published (_GoReleaser was introduced for multi-platform image publishing back in early 2022_) despite publishing a multi-platform image.
- Images of a couple hundred bytes in size with SHA256 digest sigs published as tag names (_redundant noise that shouldn't be there?_).

Originally reported here: https://github.com/ory/hydra/pull/3914#issuecomment-2571511106

> ![image](https://github.com/user-attachments/assets/886eeb84-1da0-4841-bd8b-74ebb0da6c88)

> ![image](https://github.com/user-attachments/assets/e9954d22-a253-48b5-b3cf-803113588124)

It would be ideal if that was cleaned up, or at least a fix to prevent publishing this tags in future releases.

### Reproducing the bug

Visit DockerHub for [`oryd/hydra`](https://hub.docker.com/r/oryd/hydra)

### Version

2.2.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

### Additional Context

Additional improvements:
- The [Hydra + Docker install docs](https://www.ory.sh/docs/hydra/self-hosted/install#docker) reference [`oryd/hydra`](https://hub.docker.com/r/oryd/hydra), but could also provide a link to the page as a minor convenience to the reader. Likewise on this repo README (_"Get Started" and "Develop" sections for Docker, or more commonly via another badge at the top of the README_)
- The DockerHub README directs the user to Hydra docs. It provides no additional context on the image usage or the tags available. It should note images are published with each semver variant are Alpine based, while an additional `-distroless` suffix in the tag provides an image variant using [Google's Distroless](https://github.com/GoogleContainerTools/distroless) (_Minimal Debian base image without a package manager_). Linking to the [Quickstart guide](https://www.ory.sh/docs/hydra/5min-tutorial) could be helpful since it's focused on using the image.
- Additionally, the Alpine variant is rootful and might bundle `sqlite` in future, while the `-distroless` variant is rootless and has no `sqlite` package installed. I don't personally think the image needs to be configured as rootless (_those users are probably better served by Podman or Docker in rootless mode, rather than the image_), moving from Google Distroless to Ubuntu's `chisel` would also allow a minimal glibc image which could also bundle `sqlite` if desired (_presently I discourage `chisel` for minimal images until they minimize verbosity_).

**Comment by aeneasr** [comment]
Thank you for the report, setting up gorelease can be immensely painful and frustrating so I'm happy it works at all at the moment 😓 

You can find the base config here: https://github.com/ory/xgoreleaser/blob/master/build.tmpl.yml

**Comment by polarathene** [comment]
In 2025 do you still think it's worth publishing ARM v7 and v6 binaries for releases? In a project I maintain (_15k stars mail-server dockerized service_), we [dropped ARM v7 support back in Dec 2022](https://github.com/docker-mailserver/docker-mailserver/issues/2642). There was a few users still interested IIRC, but no major complaints declaring the platform legacy and for those users to build the project themselves or spend say $50 to replace that hardware.

Might be worth considering for Ory to take the same stance going forward? Usually I see projects on Github publish for a wide variety of platforms on GH Releases just because the build platform / CI can support it, rather than actual demand for the more esoteric platforms published.

---

You should be able to drop the entire [dockers](https://github.com/ory/xgoreleaser/blob/a5d1b76dc608ec08aa9df19b7f12c0f32b0471a9/build.tmpl.yml#L396-L579) config from there shaving almost 200 lines away.

The [image labels](https://github.com/ory/xgoreleaser/blob/a5d1b76dc608ec08aa9df19b7f12c0f32b0471a9/build.tmpl.yml#L425-L432) assigned could be part of your `Dockerfile`, or centralized via Github Actions in a single step.

It's up to you if you want to keep building Hydra via GoReleaser and copy the binary during the image build, otherwise the Docker images build + publish could be managed entirely separately if that's simpler to grok and maintain.

I am not familiar with CoSign and your [usage with it for Docker](https://github.com/ory/xgoreleaser/blob/a5d1b76dc608ec08aa9df19b7f12c0f32b0471a9/build.tmpl.yml#L30-L45), but I assume that's related to the random digest `.sig` image tags being accidentally published to the image registry?

---

This would need some tweaking, and I've not accounted for the `-distroless` variant yet, but that could be handled via a separate input, or introducing some extra steps/jobs in the 2nd workflow that gets called.

It's split into two to keep the trigger workflow for your repo small and simple, with the dynamic inputs clearly visible under the `with` parameters (_these become `inputs` when referenced in the 2nd workflow_). It'd need a bit of adjustment but would allow for the 2nd workflow to be centralized at it's own repo if your other Ory projects were to share it like you do with GoReleaser 👍 


```yaml
name: 'Build and Publish Docker Images'

on:
  workflow_dispatch:
  push:
    branches:
      - master
    # Optional: Only trigger this workflow if the push event
    # involves files matching these path patterns:
    paths:
      - src/**
      - .dockerignore
      - Dockerfile
    # Release tags as an alternative trigger to branch push,
    # For example, when creating a GH Release which adds a tag:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    name: 'Deploy Docker Images'
    uses: ory/hydra/.github/workflows/generic_publish.yml@master
    with:
      project-name: hydra
      revision: ${{ github.sha }}
      source: https://github.com/${{ github.repository }}
      version: ${{ github.ref_type == 'tag' && github.ref_name || 'edge' }}
    secrets: inherit
```

```yaml
name: 'Build and Publish the Docker Image'

on:
  workflow_call:
    inputs:
      image-variant:
        required: false
        type: string
      project-name:
        required: true
        type: string
      revision:
        required: true
        type: string
      source:
        required: true
        type: string
      version:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  publish-images:
    name: 'Build and Publish'
    runs-on: ubuntu-latest
    steps:
      - name: "Get current timestamp (ISO 8601)"
        id: build-info
        run: echo "date=$(date --utc --iso-8601=seconds)" >> "${GITHUB_OUTPUT}"

      - name: 'Checkout'
        uses: actions/checkout@v4

      # This step will support building non-native platform archs via emulation (slow)
      # Skip this when you can compile for that platform natively, or cross-compile (Zig, Go)
      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      # The metadata action appends labels and sets the image names + tags to publish.
      # Tags for the image to be published, based on the following rules:
      # https://github.com/docker/metadata-action?tab=readme-ov-file#typeedge
      # https://github.com/docker/metadata-action?tab=readme-ov-file#typesemver
      # Updates to master branch will publish an image with the `:edge` tag (useful between official releases)
      # Pushing a git tag will publish an image with all 3 semver tags
      #
      # NOTE: Publishing the semver tags like this is useful for software that monitors an image
      # for updates only by a digest change to the image tag at the registry, like WatchTower does:
      # https://github.com/containrrr/watchtower/issues/1802
      #
      # NOTE: By default the `:latest` image tag will be updated for the `semver` type below,
      # you may want to have more control over that if your release policy could publish a patch
      # release to an older major/minor release (as this would unintentionally update the latest tag too):
      # https://github.com/docker/metadata-action?tab=readme-ov-file#latest-tag
      - name: 'Prepare tags'
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/oryd/${{ inputs.project-name }}
            ghcr.io/ory/${{ inputs.project-name }}
          tags: |
            type=edge,branch=master
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
          labels: |
            org.opencontainers.image.created=${{ steps.build-info.outputs.date }}
            org.opencontainers.image.title=${{ inputs.project-name }}
            org.opencontainers.image.revision=${{ inputs.revision }}
            org.opencontainers.image.source=${{ inputs.source }}
            org.opencontainers.image.version=${{ inputs.version }}
            org.opencontainers.image.vendor=Ory
            org.opencontainers.image.url=https://www.ory.sh
            org.opencontainers.image.documentation=https://www.ory.sh/docs


      # Publish to image registries (DockerHub and GHCR):
      - name: 'Login to DockerHub'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # Build the image from a Dockerfile for the requested platforms,
      # then publish a multi-platform image at the registries with the tags and labels declared above
      - name: 'Build and publish images'
        uses: docker/build-push-action@v6
        with:
          context: .
          # Customize any Dockerfile ARG values here:
          build-args: |
            BASE_IMAGE=${{ inputs.image-variant }}
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.docker-metadata.outputs.labels }}
          tags: ${{ steps.docker-metadata.outputs.tags }}
          # Disable provenance attestation: https://docs.docker.com/build/attestations/slsa-provenance/
          provenance: false
```

**NOTE:**
- You'll need to set `DOCKER_USERNAME` and `DOCKER_PASSWORD` in your repo secrets.
- The `build-info` step to get the build date for the `image.created` label could probably be replaced by the [`metadata-action` support for formatting a date](https://github.com/docker/metadata-action?tab=readme-ov-file#date-format-tztimezone) in a similar way.
- To support the `-distroless` suffix, you could probably append `,suffix=` to each tag variant, with a conditional on if `image-variant` input was defined, I've not looked into that atm (_nor the last step `build-push-action` with `build-arg` specifying `BASE_IMAGE` with an empty default_). These refer to [my `Dockerfile` proposal](https://github.com/ory/hydra/pull/3914#issuecomment-2572125066) which could self-contain the Go builder stage with the Alpine + Distroless variants both supported.
