### ISSUE TITLE
`expires_at` Missing from /admin/oauth2/auth/sessions/consent Endpoint

### ISSUE THREAD

**Issue by fmiqbal** [ory/hydra#3950]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

I didnt see `expires_at` when calling `/admin/oauth2/auth/sessions/consent` as described per docs

https://github.com/ory/hydra/blob/1520260d67f3eb331ced3897eaca54849a24b878/spec/api.json#L937-L959

![Image](https://github.com/user-attachments/assets/ddec513a-1cc3-44d9-9172-91caedded451)

![Image](https://github.com/user-attachments/assets/5d05ba28-122d-4630-bda9-8d4980f1b8e2)

### Reproducing the bug

1. Make API call to `/admin/oauth2/auth/sessions/consent` via Postman / SDK, in Postman it will not be shown, in the SDK (PHP it will become null)

### Relevant log output

```shell
No log error, just missing attribute
```

### Relevant configuration

```yml
serve:
  cookies:
    same_site_mode: Lax
    domain: "<REDACTED>"
    secure: false
    names:
      login_csrf: "<REDACTED>"
      consent_csrf: "<REDACTED>"
      session: "<REDACTED>"
  admin:
    cors:
      enabled: true
      allowed_origins:
        - "<REDACTED>"
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
        - Accept
      exposed_headers:
        - Content-Type
  public:
    cors:
      enabled: true
      allowed_origins:
        - "<REDACTED>"
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
        - Accept
      exposed_headers:
        - Content-Type

clients:
  http:
    disallow_private_ip_ranges: true

urls:
  self:
    issuer: "<REDACTED>"
  consent: "<REDACTED>"
  error: "<REDACTED>"
  login: "<REDACTED>"
  logout: "<REDACTED>"

secrets:
  system:
    - "<REDACTED>"

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: "<REDACTED>"

ttl:
  access_token: 1m
```

### Version

Docker `oryd/hydra:latest` / `v2.3.0` / oryd/hydra@sha256:b94007e19a1f7f78157e7f4ea340da8a55b5f104a0f1198755c256f38ef32b4b

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

### Additional Context

docker compose 
```yaml
  postgresd-hydra:
    image: postgres:11.8
    restart: unless-stopped
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=<REDACTED>
      - POSTGRES_PASSWORD=<REDACTED>
      - POSTGRES_DB=<REDACTED>

  hydra-migrate:
    image: oryd/hydra
    environment:
      DSN: postgres://<REDACTED>:<REDACTED>@postgresd-hydra:5432/<REDACTED>?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate sql -e --yes
    restart: on-failure

  hydra:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hydra.rule=Host(`<REDACTED>`) && (PathPrefix(`/oauth2`) || PathPrefix(`/.well-known`))"
      - "traefik.http.routers.hydra.tls=true"
      - "traefik.http.routers.hydra.entrypoints=web-secure"
      - "traefik.http.routers.hydra.service=hydra"
      - "traefik.http.services.hydra.loadbalancer.server.port=4444"
    image: oryd/hydra
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    ports:
      - "4445:4445"
    volumes:
      - type: bind
        source: ./conf/hydra/hydra.yaml
        target: /etc/config/hydra/hydra.yml
    environment:
      DSN: postgres://<REDACTED>:<REDACTED>@postgresd-hydra:5432/<REDACTED>?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: unless-stopped
    depends_on:
      - hydra-migrate
```
