### ISSUE TITLE
Permission denied for mounted SQLite volume

### ISSUE THREAD

**Issue by skaggmannen** [ory/hydra#3951]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

When mounting the SQLite database as a volume in docker compose, Hydra fails to open the database and prints an error.

### Reproducing the bug

1. Create a compose.yaml file with `/var/lib/sqlite` mounted as a volume. 
    - You can use the `compose.yaml` and `hydra.yml` files attached to this issue.
2. Run `docker compose up -d` to start the stack.
3. Check the logs for the Hydra container: `docker logs hydra-test-hydra-1`

### Relevant log output

```shell
{"audience":"application","error":{"message":"unable to open database file: no such file or directory","stack_trace":"stack trace could not be recovered from error type sqlite3.Error"},"level":"info","msg":"Retrying in 5.000000 seconds...","service_name":"Ory Hydra","service_version":"v2.3.0","time":"2025-02-26T09:54:35.775415537Z"}
```

### Relevant configuration

```yml
# compose.yml
---
name: "hydra-test"
services:
  hydra:
    restart: always
    image: oryd/hydra:v2.3.0
    command: serve all -c /etc/config/hydra/hydra.yml --dev
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: hydra.yml
        target: /etc/config/hydra/hydra.yml
    depends_on:
      - hydra-migrate
    networks:
      - internal
  hydra-migrate:
    image: oryd/hydra:v2.3.0
    command: migrate sql -c /etc/config/hydra/hydra.yml -e --yes
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: hydra.yml
        target: /etc/config/hydra/hydra.yml
    restart: on-failure
    networks:
      - internal
networks:
  internal:
volumes:
  hydra-sqlite:

# hydra.yml
---
dsn: sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
urls:
  self:
    issuer: http://localhost:4444
    public: http://localhost:4444
    admin: http://hydra:4445
  consent: http://localhost:8080/login/consent
  login: http://localhost:8080/login
  logout: http://localhost:8080/logout
  post_logout_redirect: http://localhost:8080/
serve:
  cookies:
    same_site_mode: Lax
secrets:
  system:
    - da2bc01f8bb0eb3cb55768269b837f98cfe42aca721ba2792e2e829ee844dcd0
log:
  format: json
  level: debug
```

### Version

v2.3.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

### Additional Context

It seems like `/var/lib/sqlite` no longer is writable by the container user (`nonroot`) after changes was made to `.docker/Dockerfile-alpine` in https://github.com/ory/hydra/pull/3924.
