### ISSUE TITLE
cmd: Add cli helper for importing and exporting environments (clients, policies, keys)

### ISSUE THREAD

**Issue by Rio** [ory/hydra#699]
It makes developing against hydra a bit difficult if the redirect uri for the root client is hard coded to localhost and you're trying emulate the production architecture a bit better. With for example a reverse proxy routing all traffic to the correct endpoints using urls. By allowing to overwrite the redirect uris in the same way as the root clients' credentials it would make hydra flexible while developing against it.

**Comment by arekkas** [comment]
It's not very unlikely that the root client will not be able to make any grants except the `client_credentials` grant with 1.0.0. Since it's such a highly priviledged client it shouldn't be used for anything except setting up your environment.

Creating a new client on the other hand is as easy as

```
hydra clients create -a scope1,scope2 -c http://my-callback
```

So I don't really see the need for making the root client even more configurable.

**Comment by Rio** [comment]
It could be just me not understanding Hydra well enough while developing against it. But right now to get our developers setup quickly using only a `docker-compose up` I need to run in order a `migrate`, `clients create` and a `policies create` just to get a consent app going. Since the hydra container as been rebased onto `scratch`, I can't just chain those commands using `bash` within a `hydra-init` contiainer. Instead I need to chain completely separate containers, each with their own entry in `docker-compose.yml`, just to get a single uri to point to the correct location of where my callback is listening.

This would solve it neatly in my opinion as it fits with the already established `FORCE_ROOT_CLIENT_CREDENTIALS` env var.

I'm ok with not merging this but I'd like to see how people handle the quick setup and teardown of hydra when developing against it :)

**Comment by arekkas** [comment]
Ok, that sounds really frustrating so let's try to solve this in a way that falls in line with the possiblities at hand. First of all, what you are doing can also be solved like this:

```
docker run --rm -it \
  -e CLUSTER_URL=https://ory-hydra-example--hydra:4444 \
  -e CLIENT_ID=admin \
  -e CLIENT_SECRET=demo-password \
  --network hydraguide \
  oryd/hydra:v0.10.7 \
  <command>
```

where (obviously) the network should be the network you bring up in docker compose. By the way, you can set the docker compose name prefix with `-n` or something (I'd have to look it up).

Another possibility would be to have a `init.d` directory similar to what PostgreSQL/MySQL is doing where config files are loaded from on first boot. I would need some time to think this approach over though.

In our system, we are running some bash scripts that run `hydra import` on all files of a directory. They have exponential back off so it will work even if Hydra takes 5 seconds to start on initial install.

By the way, we are also working on a few helpers that are even pluggable to GitHub's API for deploying clients, policies etc in Hydra, but that's still work in progress and will not be a completely open source product.

Is there anything where you say that makes sense?

**Comment by Rio** [comment]
The docker example you give is how we're doing it right now. But because of the way docker-compose works and the lack of a scripting lang inside of the hydra container I need to spin up a separate docker-compose service for each hydra command I want to run. 

Btw `hydra import` doesn't seem to exist, I think you meant `hydra clients import`. Sadly this doesn't exist for `policies` so that will still need to be a separate command.

The `init.d` sollution would be an ok route to go as it gives you a good amount of flexibility for dev setup.

I've also been considering to create a small go binary built off the hydra sdk that does the setup but if I'm doing that I'm inclined to just add it to the hydra cli... `hydra host --dev` or something.

I'll setup a minimal docker compose file as an example including a reverse proxy so we have something to talk about. And that way you can point out any glaring mistakes I'm making ;)

Let me here what you think.

**Comment by arekkas** [comment]
> The docker example you give is how we're doing it right now. But because of the way docker-compose works and the lack of a scripting lang inside of the hydra container I need to spin up a separate docker-compose service for each hydra command I want to run.

I'm not sure I'm getting this. You can attach a docker run command do a network created by docker compose, as seen here:

```
docker network ls
NETWORK ID          NAME                                    DRIVER              SCOPE
ad2a7d116d21        bridge                                  bridge              local
a8b5ee5b9e29        compose_ory-am-example-project-subnet   bridge              local
ba4a8561b699        compose_platform-subnet                 bridge              local
911567b847f7        host                                    host                local
4938a70da3a1        hydraconsentappauth0_subnet             bridge              local
aa763277996f        none                                    null                local
```

Typically `docker-compose` uses the canonicalized (no spaces iirc) directory name as prefix. You can override this with `docker-compose -p someprefix <command>`. Then you can easily run a docker run command that connects to the network, identified by `<prefix>_<network-name>`.

> Sadly this doesn't exist for policies so that will still need to be a separate command.

I can proudly say that it does. Unfortunately, it's not consistent with `clients import` (had this in the back of my head for a while, good that we're seeing this in the wild now -> #701 ).

Hope this helps.

**Comment by Rio** [comment]
Ah my bad for missing the `policies import` equiv.

I'm sorry if I'm not being clear enough. Our problem is not not being able to connect to the containers that part is fine. Our problem is with the assumption that our callback is running on `http://localhost:4445/callback` as it is set in the root client. The callback is running on some equivalent of `http://projectx.localhost/api/auth/callback`.

So in order to get the client to actually get to the callback it has to be routed through a reverse proxy just like all our other services. This is a reflection as how our production environment is running but locally with docker-compose.

In order to get to that point and setup the redirect uri for the client I need to go through all the configuration steps of setting up migrations, creating a client, creating a policy, and then create another client and policy to be able to complete the OAuth2 flow. Usually I'd just string those commands together within the hydra container using bash. But now because there is no more bash in the container there is not easy way to run those commands without having the developer install hydra on their machine and running a shell script. Or as I said before building a custom go binary that uses the SDK to do the setup.

I hope this explains it a bit better.

**Comment by arekkas** [comment]
While it's not the most beautiful, you can chain commands in the image like this:

```
$ docker -rm -it /.../ \
     clients create /.../ \
       && hydra foo bar \
       & & hydra bar bar
```

The other alternative would be to have a global import (maybe init?) command `hydra import` / `hydra init` which creates the database schemas and imports a JSON file containing clients / keys / policies / groups:

```
{
  clients: [],
  keys: [],
  policies: [],
  groups: []
}
```

This would also allow us to do something like `hydra export` although it won't be possible to export existing tokens/consent flows/client secrets.

**Comment by arekkas** [comment]
This could actually be a good idea. We could provide example configs here that set up e.g. a development environment, or something more advanced. I kind of like this idea!

**Comment by Rio** [comment]
I've just finished a docker-compose file that sort of reflects our setup based on https://ory.gitbooks.io/hydra/content/install.html I haven't tested if it actually works and it's missing the consent app and consumer app.

**Comment by Rio** [comment]
```docker-compose
version: "3.3"

services:
  traefik:
    image: docker.io/traefik
    command:
      - --web
      - --accesslog
      - --file
      - --file.filename=/etc/traefik/rules.toml
    ports:
      - "80:80"
    volumes:
      - ./traefik:/etc/traefik:z

  postgres:
    image: docker.io/postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

  hydra-init:
    image: $HYDRA_IMAGE_TAG
    command: migrate sql postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?sslmode=disable
    depends_on:
      - postgres

  hydra:
    image: $HYDRA_IMAGE_TAG
    command: host --dangerous-force-http
    depends_on:
      - hydra-init
    environment:
      SYSTEM_SECRET: $SYSTEM_SECRET
      DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?sslmode=disable
      ISSUER: http://projectx.localhost/api/auth
      CONSENT_URL: http://projectx.localhost/api/rest/v1alpha1/consent
      FORCE_ROOT_CLIENT_CREDENTIALS: $HYDRA_ROOT_CLIENT_ID:$HYDRA_ROOT_CLIENT_SECRET
      DISABLE_TELEMETRY: "1"

  hydra-create-consent-client:
    image: $HYDRA_IMAGE_TAG
    command: clients create --id $CONSENT_APP_CLIENT_ID --secret $CONSENT_APP_CLIENT_SECRET --name "Consent App Client" --grant-types client_credentials --response-types token --allowed-scopes hydra.consent
    depends_on:
      - hydra
    environment:
      CLUSTER_URL: $HYDRA_CLUSTER_URL
      CLIENT_ID: $HYDRA_ROOT_CLIENT_ID
      CLIENT_SECRET: $HYDRA_ROOT_CLIENT_SECRET

  hydra-create-consent-policy:
    image: $HYDRA_IMAGE_TAG
    command: policies create --actions get,accept,reject --allow --id concent-app-policy --resources "rn:hydra:oauth2:consent:requests:<.*>" --subjects $CONSENT_APP_CLIENT_ID
    depends_on:
      - hydra-create-consent-client
    environment:
      CLUSTER_URL: $HYDRA_CLUSTER_URL
      CLIENT_ID: $HYDRA_ROOT_CLIENT_ID
      CLIENT_SECRET: $HYDRA_ROOT_CLIENT_SECRET

  hydra-create-consumer-client:
    image: $HYDRA_IMAGE_TAG
    command: clients create --id $CONSUMER_CLIENT_ID --secret $CONSUMER_CLIENT_SECRET --name "Consumer App Client" --callbacks http://projectx.localhost/api/callback --grant-types authorization_code,refresh_token,client_credentials --response-types token,id_token,code --allowed-scopes openid,offline,hydra.clients
    depends_on:
      - hydra
    environment:
      CLUSTER_URL: $HYDRA_CLUSTER_URL
      CLIENT_ID: $HYDRA_ROOT_CLIENT_ID
      CLIENT_SECRET: $HYDRA_ROOT_CLIENT_SECRET

  hydra-create-openid-id_token-policy:
    image: $HYDRA_IMAGE_TAG
    command: policies create --actions get --allow --id openid-id_token-policy --resources "rn:hydra:keys:hydra.openid.id-token:public" --subjects "<.*>"
    depends_on:
      - hydra
    environment:
      CLUSTER_URL: $HYDRA_CLUSTER_URL
      CLIENT_ID: $HYDRA_ROOT_CLIENT_ID
      CLIENT_SECRET: $HYDRA_ROOT_CLIENT_SECRET
```

**Comment by Rio** [comment]
Here is the accompanying `traefik/rules.toml` file and `.env`.

```bash
HYDRA_IMAGE_TAG=docker.io/oryd/hydra:v0.10.7
SYSTEM_SECRET=very-secure-and-quite-long-system-secret-that-should-not-change-between-runs
HYDRA_CLUSTER_URL=http://hydra:4444
HYDRA_ROOT_CLIENT_ID=admin
HYDRA_ROOT_CLIENT_SECRET=admin-secret

POSTGRES_USER=hydra-user
POSTGRES_PASSWORD=hydra-password
POSTGRES_DB=hydra

CONSENT_APP_CLIENT_ID=consent-app
CONSENT_APP_CLIENT_SECRET=consent-app-secret

CONSUMER_CLIENT_ID=consumer-app
CONSUMER_CLIENT_SECRET=consumer-app-secret
```

```toml
[backends]
    [backends.traefik]
        [backends.traefik.servers.server1]
        url = "http://traefik:8080"

    [backends.hydra]
        [backends.hydra.servers.server1]
        url = "http://hydra:4444"

[frontends]
    [frontends.traefik]
    backend = "traefik"
    passHostHeader = true
        [frontends.traefik.routes.route1]
        rule = "Host: traefik.projectx.localhost"

    [frontends.hydra]
    backend = "hydra"
        [frontends.hydra.routes.route1]
        rule = "PathPrefixStrip: /api/auth"
```

**Comment by arekkas** [comment]
I see your pain :D How do you feel about: https://github.com/ory/hydra/issues/699#issuecomment-351013866

**Comment by Rio** [comment]
That would help a quite a bit. reducing setup to just `hydra migrate sql` and `hydra import ./thingy.json`.
But I think you see now why I went the adding an override for the root client's redirect uri route ;)

Also adding a simple `/bin/sh` implementation in the container would help in the short term as well because we could string all those commands in a single `docker run` statement like you suggested also in that comment but currently doesn't work.

**Comment by Rio** [comment]
oh and mind you, this is just setting up hydra and traefik. We've also got minio, cockroach, mysql, mailhog, jaeger just to name a few supporting services. Not even mentioning our own 20+ services...

**Comment by arekkas** [comment]
> oh and mind you, this is just setting up hydra and traefik. We've also got minio, cockroach, mysql, mailhog, jaeger just to name a few supporting services. Not even mentioning our own 20+ services...

Micro service automation is very hard.

> Also adding a simple /bin/sh implementation in the container would help in the short term as well because we could string all those commands in a single docker run statement like you suggested also in that comment but currently doesn't work.

We could add an `-alpine` image to the docker build chain.

**Comment by Rio** [comment]
> We could add an -alpine image to the docker build chain.

That would be a solution that wouldn't need any actual code changes. And people could opt in for it.

**Comment by arekkas** [comment]
> That would be a solution that wouldn't need any actual code changes. And people could opt in to it.

Ok let's go for this now and introduce some elaborate way to deal with this at a later stage.

Tracked as #703

**Comment by Rio** [comment]
This is way better now thanks!

```
  hydra:
    image: $HYDRA_IMAGE_ALPINE
    entrypoint: ["/bin/sh", "-c"]
    command: |
      'hydra migrate sql $$DATABASE_URL &&
       hydra host --dangerous-force-http'
    depends_on:
      - postgres
    environment:
      SYSTEM_SECRET: $SYSTEM_SECRET
      DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?sslmode=disable
      ISSUER: http://projectx.localhost/api/auth
      CONSENT_URL: http://projectx.localhost/api/rest/v1alpha1/auth/consent
      FORCE_ROOT_CLIENT_CREDENTIALS: $HYDRA_ROOT_CLIENT_ID:$HYDRA_ROOT_CLIENT_SECRET
      DISABLE_TELEMETRY: "1"

  hydra-init:
    image: $HYDRA_IMAGE_ALPINE
    entrypoint: ["/bin/sh", "-c"]
    command: |
      'hydra clients import /etc/hydra/thingy.json &&
       hydra policies create -f /etc/hydra/other-thingy.json'
    depends_on:
      - hydra
    environment:
      CLUSTER_URL: http://hydra:4444
      CLIENT_ID: $HYDRA_ROOT_CLIENT_ID
      CLIENT_SECRET: $HYDRA_ROOT_CLIENT_SECRET
    volumes:
      - ./hydra:/etc/hydra:z
```

**Comment by arekkas** [comment]
You could have solved this with the stratch image:

```
  hydra:
    image: $HYDRA_IMAGE_SCRATCH
    command: |
      'migrate sql $$DATABASE_URL &&
       hydra host --dangerous-force-http'
    depends_on:
      - postgres
    environment:
      SYSTEM_SECRET: $SYSTEM_SECRET
      DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?sslmode=disable
      ISSUER: http://projectx.localhost/api/auth
      CONSENT_URL: http://projectx.localhost/api/rest/v1alpha1/auth/consent
      FORCE_ROOT_CLIENT_CREDENTIALS: $HYDRA_ROOT_CLIENT_ID:$HYDRA_ROOT_CLIENT_SECRET
      DISABLE_TELEMETRY: "1"
```
