### ISSUE TITLE
Public and private key pair fetched from store does not match

### ISSUE THREAD

**Issue by tpoxa** [ory/hydra#912]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

public and private key pair fetched from store does not match

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

```
version: '3'

services:
  hydra_migrate:
    build:
      context: .
      dockerfile: Dockerfile
    image: "hydra"
    environment:
#      - LOG_LEVEL=debug
       DATABASE_URL: "postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable"
       SYSTEM_SECRET: "NWM4M2I3OGY1MTRmYTM5ZDEwNjBhODVl"
    command: "migrate sql -e"
    restart: on-failure
    networks:
      - hydra
    depends_on:
      - postgresd
  hydra:
    build:
      context: .
      dockerfile: Dockerfile
    image: "hydra"
    depends_on:
      - hydra_migrate
    ports:
      - "4444:4444"
      - "4445:4445"
    command: "serve --dangerous-force-http"
    environment:
#      - LOG_LEVEL=debug
        OAUTH2_ISSUER_URL: http://localhost:4444
        OAUTH2_CONSENT_URL: http://localhost:3000/consent
        OAUTH2_LOGIN_URL: http://localhost:3000/login
        DATABASE_URL: postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
        SYSTEM_SECRET: "NWM4M2I3OGY1MTRmYTM5ZDEwNjBhODVl"
        OAUTH2_SHARE_ERROR_DEBUG: 1
    restart: unless-stopped
    networks:
      - hydra
  consent:
    environment:
      - HYDRA_URL=http://hydra:4444
    image: oryd/hydra-login-consent-node:v1.0.0-beta.1
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - hydra
    depends_on:
      - hydra

  postgresd:
    image: postgres
    restart: always
    volumes:
      - hydradb_vol4:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
        POSTGRES_USER: hydra
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: hydra
    networks:
      - hydra  

volumes:
  hydradb_vol4:
  
networks:
  hydra:
    driver: overlay
    
```
```
docker-compose up
```

**What is the expected behavior?**
oh

**Which version of the software is affected?**
master branch
golang 1.10
